import { seccion } from "./seccion";

export default seccion(
  {
    "bandeja.abriendo": "Abriendo tu bandeja…",
    "bandeja.errorCarga": "No se ha podido cargar la bandeja. Tira hacia abajo para reintentar.",
    "bandeja.faltaClave":
      "Las notas, los informes y los avisos llegan cerrados con tu clave, y solo se abren donde está guardada. Escribe el código de recuperación que apuntaste en el alta: la clave se reconstruye aquí y no sale del móvil.",
    "bandeja.vacia":
      "No tienes mensajes. Aquí llegan las notas que te deja el veterinario después de una consulta, los informes de tu clínica habitual y los avisos de una clínica si alguien lleva a tu mascota perdida.",
    "bandeja.seleccionarMensajes": "Seleccionar mensajes",
    "bandeja.seleccionarTodos": "Seleccionar todos",
    "bandeja.quitarTodos": "Quitar todos",
    "bandeja.borrarSeleccion.uno": "Borrar 1 seleccionado",
    "bandeja.borrarSeleccion.varios": "Borrar {n} seleccionados",
    "bandeja.borrarVarios.uno": "¿Borrar 1 mensaje?",
    "bandeja.borrarVarios.varios": "¿Borrar {n} mensajes?",
    "bandeja.borrarVariosTexto":
      "Se borran del servidor y no se pueden recuperar. Si hay notas o informes que quieras conservar, guárdalos antes por tu cuenta.",
    "bandeja.borrarUno": "¿Borrar este mensaje?",
    "bandeja.borrarUnoTexto":
      "Se borra del servidor y no se puede recuperar. Si es una nota o un informe y lo quieres conservar, guárdalo antes por tu cuenta.",
    "bandeja.errorBorrar": "No se ha podido borrar",
    "bandeja.seleccionar": "Seleccionar",
    "bandeja.seleccionado": "Seleccionado",
    "bandeja.seleccionarMensaje": "Seleccionar: {titulo}",
    "bandeja.titulo.aviso": "Una clínica tiene a {nombre}",
    "bandeja.titulo.nota": "Nota de la consulta",
    "bandeja.titulo.informe": "Informe de la clínica",
    "bandeja.titulo.firmaMala": "Registro con una firma que no cuadra",
    "bandeja.titulo.ilegible": "Mensaje que no se puede abrir",
    "bandeja.tipo.aviso": "Aviso",
    "bandeja.tipo.nota": "Nota de consulta",
    "bandeja.tipo.informe": "Informe",
    "bandeja.tipo.certificado": "Pasaporte",
    "bandeja.tipo.firmaMala": "Sin validar",
    "bandeja.tipo.ilegible": "Sin abrir",
    "bandeja.enviadoDominio": "Enviado por {clinica} · {dominio}, dominio verificado · desde su software de gestión",
    "bandeja.enviadoPais": "Enviado por {clinica} · {pais} · desde su software de gestión",
    "bandeja.aviso.unaClinica": "Una clínica veterinaria",
    "bandeja.aviso.texto": "{clinica} ha leído el chip de {nombre} y quiere hablar contigo.",
    "bandeja.aviso.textoMotivo": "{clinica} ha leído el chip de {nombre} y quiere hablar contigo: «{motivo}»",
    "bandeja.aviso.llamar": "Llamar a la clínica · {telefono}",
    "bandeja.campo.clinica": "Clínica",
    "bandeja.campo.fecha": "Fecha",
    "bandeja.campo.veterinario": "Veterinario",
    "bandeja.campo.diagnostico": "Diagnóstico",
    "bandeja.campo.tratamiento": "Tratamiento",
    "bandeja.campo.observaciones": "Observaciones",
    "bandeja.informeFirmado": "Firma de la clínica comprobada en este móvil.",
    "bandeja.certificadoNota":
      "Firma de la clínica comprobada. Se guarda en el pasaporte de viaje al abrirlo en el portal web.",
    "bandeja.firmaMalaTexto":
      "Dice venir de tu clínica, pero la firma no es la de su conexión con Bark & Meow. Si esperabas un registro, pregunta a tu clínica.",
    "bandeja.ilegibleTexto": "No se ha podido abrir con tu clave. Puede estar dañado o sellado para otra clave.",
    // Registros de viaje firmados (lib/bandeja.ts, también en el pasaporte).
    "bandeja.reg.vacunaRabia": "Vacuna de la rabia",
    "bandeja.reg.vacuna": "Vacuna",
    "bandeja.reg.vacunaDe": "Vacuna: {nombre}",
    "bandeja.reg.tenia": "Tratamiento contra la tenia",
    "bandeja.reg.desparasitacion": "Desparasitación",
    "bandeja.reg.titulacion": "Análisis de anticuerpos de la rabia",
    "bandeja.reg.registro": "Registro",
    "bandeja.reg.lote": "lote {lote}",
    "bandeja.reg.validaHasta": "válida hasta {fecha}",
    "bandeja.reg.muestra": "muestra del {fecha}",
  },
  {
    pt: {
      "bandeja.abriendo": "A abrir a tua caixa de entrada…",
      "bandeja.errorCarga": "Não foi possível carregar a caixa de entrada. Puxa para baixo para tentar de novo.",
      "bandeja.faltaClave":
        "As notas, os relatórios e os avisos chegam fechados com a tua chave e só se abrem onde ela está guardada. Escreve o código de recuperação que apontaste no registo: a chave reconstrói-se aqui e não sai do telemóvel.",
      "bandeja.vacia":
        "Não tens mensagens. Aqui chegam as notas que o veterinário te deixa depois de uma consulta, os relatórios da tua clínica habitual e os avisos de uma clínica se alguém lá levar o teu animal perdido.",
      "bandeja.seleccionarMensajes": "Selecionar mensagens",
      "bandeja.seleccionarTodos": "Selecionar todas",
      "bandeja.quitarTodos": "Desmarcar todas",
      "bandeja.borrarSeleccion.uno": "Apagar 1 selecionada",
      "bandeja.borrarSeleccion.varios": "Apagar {n} selecionadas",
      "bandeja.borrarVarios.uno": "Apagar 1 mensagem?",
      "bandeja.borrarVarios.varios": "Apagar {n} mensagens?",
      "bandeja.borrarVariosTexto":
        "São apagadas do servidor e não podem ser recuperadas. Se houver notas ou relatórios que queiras guardar, guarda-os antes por tua conta.",
      "bandeja.borrarUno": "Apagar esta mensagem?",
      "bandeja.borrarUnoTexto":
        "É apagada do servidor e não pode ser recuperada. Se for uma nota ou um relatório e o quiseres guardar, guarda-o antes por tua conta.",
      "bandeja.errorBorrar": "Não foi possível apagar",
      "bandeja.seleccionar": "Selecionar",
      "bandeja.seleccionado": "Selecionada",
      "bandeja.seleccionarMensaje": "Selecionar: {titulo}",
      "bandeja.titulo.aviso": "{nombre} está numa clínica",
      "bandeja.titulo.nota": "Nota da consulta",
      "bandeja.titulo.informe": "Relatório da clínica",
      "bandeja.titulo.firmaMala": "Registo com uma assinatura que não bate certo",
      "bandeja.titulo.ilegible": "Mensagem que não se consegue abrir",
      "bandeja.tipo.aviso": "Aviso",
      "bandeja.tipo.nota": "Nota de consulta",
      "bandeja.tipo.informe": "Relatório",
      "bandeja.tipo.certificado": "Passaporte",
      "bandeja.tipo.firmaMala": "Por validar",
      "bandeja.tipo.ilegible": "Por abrir",
      "bandeja.enviadoDominio": "Enviado por {clinica} · {dominio}, domínio verificado · a partir do seu software de gestão",
      "bandeja.enviadoPais": "Enviado por {clinica} · {pais} · a partir do seu software de gestão",
      "bandeja.aviso.unaClinica": "Uma clínica veterinária",
      "bandeja.aviso.texto": "{clinica} leu o chip de {nombre} e quer falar contigo.",
      "bandeja.aviso.textoMotivo": "{clinica} leu o chip de {nombre} e quer falar contigo: «{motivo}»",
      "bandeja.aviso.llamar": "Ligar para a clínica · {telefono}",
      "bandeja.campo.clinica": "Clínica",
      "bandeja.campo.fecha": "Data",
      "bandeja.campo.veterinario": "Veterinário",
      "bandeja.campo.diagnostico": "Diagnóstico",
      "bandeja.campo.tratamiento": "Tratamento",
      "bandeja.campo.observaciones": "Observações",
      "bandeja.informeFirmado": "Assinatura da clínica verificada neste telemóvel.",
      "bandeja.certificadoNota":
        "Assinatura da clínica verificada. Fica guardado no passaporte de viagem quando o abrires no portal web.",
      "bandeja.firmaMalaTexto":
        "Diz vir da tua clínica, mas a assinatura não é a da ligação dela à Bark & Meow. Se estavas à espera de um registo, pergunta à tua clínica.",
      "bandeja.ilegibleTexto":
        "Não foi possível abri-la com a tua chave. Pode estar danificada ou selada para outra chave.",
      "bandeja.reg.vacunaRabia": "Vacina da raiva",
      "bandeja.reg.vacuna": "Vacina",
      "bandeja.reg.vacunaDe": "Vacina: {nombre}",
      "bandeja.reg.tenia": "Tratamento contra a ténia",
      "bandeja.reg.desparasitacion": "Desparasitação",
      "bandeja.reg.titulacion": "Análise de anticorpos da raiva",
      "bandeja.reg.registro": "Registo",
      "bandeja.reg.lote": "lote {lote}",
      "bandeja.reg.validaHasta": "válida até {fecha}",
      "bandeja.reg.muestra": "amostra de {fecha}",
    },
    en: {
      "bandeja.abriendo": "Opening your inbox…",
      "bandeja.errorCarga": "Couldn't load your inbox. Pull down to try again.",
      "bandeja.faltaClave":
        "Notes, reports and alerts arrive locked with your key, and they only open where it's saved. Enter the recovery code you wrote down when you signed up: the key is rebuilt here and never leaves the phone.",
      "bandeja.vacia":
        "You have no messages. This is where you'll get notes from your vet after an appointment, reports from your usual clinic, and alerts from a clinic if someone brings in your lost pet.",
      "bandeja.seleccionarMensajes": "Select messages",
      "bandeja.seleccionarTodos": "Select all",
      "bandeja.quitarTodos": "Deselect all",
      "bandeja.borrarSeleccion.uno": "Delete 1 selected",
      "bandeja.borrarSeleccion.varios": "Delete {n} selected",
      "bandeja.borrarVarios.uno": "Delete 1 message?",
      "bandeja.borrarVarios.varios": "Delete {n} messages?",
      "bandeja.borrarVariosTexto":
        "They're deleted from the server and can't be recovered. If there are notes or reports you want to keep, save them yourself first.",
      "bandeja.borrarUno": "Delete this message?",
      "bandeja.borrarUnoTexto":
        "It's deleted from the server and can't be recovered. If it's a note or a report you want to keep, save it yourself first.",
      "bandeja.errorBorrar": "Couldn't delete",
      "bandeja.seleccionar": "Select",
      "bandeja.seleccionado": "Selected",
      "bandeja.seleccionarMensaje": "Select: {titulo}",
      "bandeja.titulo.aviso": "A clinic has {nombre}",
      "bandeja.titulo.nota": "Appointment note",
      "bandeja.titulo.informe": "Clinic report",
      "bandeja.titulo.firmaMala": "Record with a signature that doesn't match",
      "bandeja.titulo.ilegible": "Message that can't be opened",
      "bandeja.tipo.aviso": "Alert",
      "bandeja.tipo.nota": "Appointment note",
      "bandeja.tipo.informe": "Report",
      "bandeja.tipo.certificado": "Passport",
      "bandeja.tipo.firmaMala": "Not verified",
      "bandeja.tipo.ilegible": "Not opened",
      "bandeja.enviadoDominio": "Sent by {clinica} · {dominio}, verified domain · from their practice software",
      "bandeja.enviadoPais": "Sent by {clinica} · {pais} · from their practice software",
      "bandeja.aviso.unaClinica": "A veterinary clinic",
      "bandeja.aviso.texto": "{clinica} has read {nombre}'s chip and wants to talk to you.",
      "bandeja.aviso.textoMotivo": "{clinica} has read {nombre}'s chip and wants to talk to you: “{motivo}”",
      "bandeja.aviso.llamar": "Call the clinic · {telefono}",
      "bandeja.campo.clinica": "Clinic",
      "bandeja.campo.fecha": "Date",
      "bandeja.campo.veterinario": "Vet",
      "bandeja.campo.diagnostico": "Diagnosis",
      "bandeja.campo.tratamiento": "Treatment",
      "bandeja.campo.observaciones": "Notes",
      "bandeja.informeFirmado": "Clinic signature checked on this phone.",
      "bandeja.certificadoNota":
        "Clinic signature checked. It's saved to the travel passport when you open it on the web portal.",
      "bandeja.firmaMalaTexto":
        "It claims to come from your clinic, but the signature isn't the one from its connection to Bark & Meow. If you were expecting a record, ask your clinic.",
      "bandeja.ilegibleTexto": "Couldn't open it with your key. It may be damaged or locked for a different key.",
      "bandeja.reg.vacunaRabia": "Rabies vaccine",
      "bandeja.reg.vacuna": "Vaccine",
      "bandeja.reg.vacunaDe": "Vaccine: {nombre}",
      "bandeja.reg.tenia": "Tapeworm treatment",
      "bandeja.reg.desparasitacion": "Deworming",
      "bandeja.reg.titulacion": "Rabies antibody test",
      "bandeja.reg.registro": "Record",
      "bandeja.reg.lote": "batch {lote}",
      "bandeja.reg.validaHasta": "valid until {fecha}",
      "bandeja.reg.muestra": "sample from {fecha}",
    },
    fr: {
      "bandeja.abriendo": "Ouverture de vos messages…",
      "bandeja.errorCarga": "Impossible de charger vos messages. Tirez vers le bas pour réessayer.",
      "bandeja.faltaClave":
        "Les notes, les comptes rendus et les alertes arrivent verrouillés avec votre clé et ne s'ouvrent que là où elle est enregistrée. Saisissez le code de récupération noté lors de l'inscription : la clé est reconstituée ici et ne quitte pas le téléphone.",
      "bandeja.vacia":
        "Vous n'avez aucun message. Ici arrivent les notes de votre vétérinaire après une consultation, les comptes rendus de votre clinique habituelle et les alertes d'une clinique si quelqu'un y amène votre animal perdu.",
      "bandeja.seleccionarMensajes": "Sélectionner des messages",
      "bandeja.seleccionarTodos": "Tout sélectionner",
      "bandeja.quitarTodos": "Tout désélectionner",
      "bandeja.borrarSeleccion.uno": "Supprimer 1 message sélectionné",
      "bandeja.borrarSeleccion.varios": "Supprimer {n} messages sélectionnés",
      "bandeja.borrarVarios.uno": "Supprimer 1 message ?",
      "bandeja.borrarVarios.varios": "Supprimer {n} messages ?",
      "bandeja.borrarVariosTexto":
        "Ils sont supprimés du serveur et ne peuvent pas être récupérés. S'il y a des notes ou des comptes rendus à conserver, enregistrez-les d'abord de votre côté.",
      "bandeja.borrarUno": "Supprimer ce message ?",
      "bandeja.borrarUnoTexto":
        "Il est supprimé du serveur et ne peut pas être récupéré. Si c'est une note ou un compte rendu à conserver, enregistrez-le d'abord de votre côté.",
      "bandeja.errorBorrar": "Impossible de supprimer",
      "bandeja.seleccionar": "Sélectionner",
      "bandeja.seleccionado": "Sélectionné",
      "bandeja.seleccionarMensaje": "Sélectionner : {titulo}",
      "bandeja.titulo.aviso": "{nombre} est dans une clinique",
      "bandeja.titulo.nota": "Note de consultation",
      "bandeja.titulo.informe": "Compte rendu de la clinique",
      "bandeja.titulo.firmaMala": "Document avec une signature qui ne correspond pas",
      "bandeja.titulo.ilegible": "Message impossible à ouvrir",
      "bandeja.tipo.aviso": "Alerte",
      "bandeja.tipo.nota": "Note de consultation",
      "bandeja.tipo.informe": "Compte rendu",
      "bandeja.tipo.certificado": "Passeport",
      "bandeja.tipo.firmaMala": "Non vérifié",
      "bandeja.tipo.ilegible": "Non ouvert",
      "bandeja.enviadoDominio": "Envoyé par {clinica} · {dominio}, domaine vérifié · depuis son logiciel de gestion",
      "bandeja.enviadoPais": "Envoyé par {clinica} · {pais} · depuis son logiciel de gestion",
      "bandeja.aviso.unaClinica": "Une clinique vétérinaire",
      "bandeja.aviso.texto": "{clinica} a lu la puce de {nombre} et souhaite vous parler.",
      "bandeja.aviso.textoMotivo": "{clinica} a lu la puce de {nombre} et souhaite vous parler : « {motivo} »",
      "bandeja.aviso.llamar": "Appeler la clinique · {telefono}",
      "bandeja.campo.clinica": "Clinique",
      "bandeja.campo.fecha": "Date",
      "bandeja.campo.veterinario": "Vétérinaire",
      "bandeja.campo.diagnostico": "Diagnostic",
      "bandeja.campo.tratamiento": "Traitement",
      "bandeja.campo.observaciones": "Observations",
      "bandeja.informeFirmado": "Signature de la clinique vérifiée sur ce téléphone.",
      "bandeja.certificadoNota":
        "Signature de la clinique vérifiée. Il est enregistré dans le passeport de voyage quand vous l'ouvrez sur le portail web.",
      "bandeja.firmaMalaTexto":
        "Il dit venir de votre clinique, mais la signature n'est pas celle de sa connexion à Bark & Meow. Si vous attendiez un document, demandez à votre clinique.",
      "bandeja.ilegibleTexto":
        "Impossible de l'ouvrir avec votre clé. Il est peut-être abîmé ou verrouillé pour une autre clé.",
      "bandeja.reg.vacunaRabia": "Vaccin contre la rage",
      "bandeja.reg.vacuna": "Vaccin",
      "bandeja.reg.vacunaDe": "Vaccin : {nombre}",
      "bandeja.reg.tenia": "Traitement contre le ténia",
      "bandeja.reg.desparasitacion": "Vermifuge",
      "bandeja.reg.titulacion": "Titrage des anticorps antirabiques",
      "bandeja.reg.registro": "Document",
      "bandeja.reg.lote": "lot {lote}",
      "bandeja.reg.validaHasta": "valable jusqu'au {fecha}",
      "bandeja.reg.muestra": "prélèvement du {fecha}",
    },
  },
);
