/* Compartir el historial con un veterinario durante unas horas. Las
   duraciones y «Enviar el enlace» también las usa el pasaporte de viaje. */

import { seccion } from "./seccion";

export default seccion(
  {
    "compartir.titulo": "Compartir con un veterinario",
    "compartir.intro": "Para una consulta fuera de casa: un enlace que enseña el historial y caduca solo.",
    "compartir.antesFicha": "Antes, la ficha de salud",
    "compartir.antesFichaTexto":
      "Lo que se enseña es la ficha de {nombre}: sus alergias, lo que toma y sus enfermedades. Escríbela primero y vuelve aquí.",
    "compartir.antesFichaTextoSin":
      "Lo que se enseña es la ficha de tu mascota: sus alergias, lo que toma y sus enfermedades. Escríbela primero y vuelve aquí.",
    "compartir.escribirFicha": "Escribir la ficha de salud",
    "compartir.errorCrear": "No se ha podido crear el enlace",
    "compartir.retirarPregunta": "¿Retirar este enlace?",
    "compartir.retirarTexto": "Dejará de abrirse al momento. Lo que alguien vio no se puede borrar.",
    "compartir.retirarSi": "Sí, retirarlo",
    "compartir.errorRetirar": "No se ha podido retirar",
    "compartir.qrTitulo": "Enséñale este QR",
    "compartir.qrEtiqueta": "Código QR del enlace al historial",
    "compartir.qrTexto": "El veterinario lo escanea con su móvil. Vale hasta el {dia} a las {hora}.",
    "compartir.lleva": "Lleva la ficha de salud.",
    "compartir.llevaUno": "Lleva la ficha de salud y un registro de vacunas, tratamientos y notas.",
    "compartir.llevaVarios": "Lleva la ficha de salud y {n} registros de vacunas, tratamientos y notas.",
    "compartir.guardalo": "Guárdalo ahora: la clave va en el propio enlace y no se puede volver a mostrar.",
    "compartir.enviar": "Enviar el enlace",
    "compartir.crearTitulo": "Crear un enlace",
    "compartir.duracion": "Cuánto tiempo vale",
    "compartir.duracion.24": "24 horas",
    "compartir.duracion.72": "3 días",
    "compartir.duracion.168": "7 días",
    "compartir.crear": "Crear el enlace",
    "compartir.crearTexto":
      "Verá la ficha de salud, las vacunas y tratamientos que constan y las notas de consultas anteriores, en su idioma y sin crear una cuenta. Puede dejarte la nota de la visita: te llega cifrada a la bandeja.",
    "compartir.abiertos": "Enlaces que siguen abiertos",
    "compartir.abiertosTexto": "Los de esta pantalla y los del pasaporte de viaje.",
    "compartir.creado": "Creado el {fecha}",
    "compartir.valeHasta": "Vale hasta el {dia} a las {hora}",
    "compartir.retirar": "Retirar",
  },
  {
    pt: {
      "compartir.titulo": "Partilhar com um veterinário",
      "compartir.intro": "Para uma consulta fora de casa: uma ligação que mostra o historial e expira sozinha.",
      "compartir.antesFicha": "Primeiro, a ficha de saúde",
      "compartir.antesFichaTexto":
        "O que se mostra é a ficha de {nombre}: as alergias, o que toma e as doenças. Preenche-a primeiro e volta aqui.",
      "compartir.antesFichaTextoSin":
        "O que se mostra é a ficha do teu animal: as alergias, o que toma e as doenças. Preenche-a primeiro e volta aqui.",
      "compartir.escribirFicha": "Preencher a ficha de saúde",
      "compartir.errorCrear": "Não foi possível criar a ligação",
      "compartir.retirarPregunta": "Retirar esta ligação?",
      "compartir.retirarTexto": "Deixa de abrir de imediato. O que alguém já viu não se pode apagar.",
      "compartir.retirarSi": "Sim, retirar",
      "compartir.errorRetirar": "Não foi possível retirar",
      "compartir.qrTitulo": "Mostra-lhe este QR",
      "compartir.qrEtiqueta": "Código QR da ligação ao historial",
      "compartir.qrTexto": "O veterinário lê-o com o telemóvel. É válido até {dia} às {hora}.",
      "compartir.lleva": "Inclui a ficha de saúde.",
      "compartir.llevaUno": "Inclui a ficha de saúde e um registo de vacinas, tratamentos e notas.",
      "compartir.llevaVarios": "Inclui a ficha de saúde e {n} registos de vacinas, tratamentos e notas.",
      "compartir.guardalo": "Guarda-a agora: a chave vai na própria ligação e não se pode voltar a mostrar.",
      "compartir.enviar": "Enviar a ligação",
      "compartir.crearTitulo": "Criar uma ligação",
      "compartir.duracion": "Quanto tempo é válida",
      "compartir.duracion.24": "24 horas",
      "compartir.duracion.72": "3 dias",
      "compartir.duracion.168": "7 dias",
      "compartir.crear": "Criar a ligação",
      "compartir.crearTexto":
        "Vai ver a ficha de saúde, as vacinas e tratamentos que constam e as notas de consultas anteriores, no idioma dele e sem criar conta. Pode deixar-te a nota da consulta: chega-te cifrada à caixa de entrada.",
      "compartir.abiertos": "Ligações ainda abertas",
      "compartir.abiertosTexto": "As deste ecrã e as do passaporte de viagem.",
      "compartir.creado": "Criada a {fecha}",
      "compartir.valeHasta": "Válida até {dia} às {hora}",
      "compartir.retirar": "Retirar",
    },
    en: {
      "compartir.titulo": "Share with a vet",
      "compartir.intro": "For a visit away from home: a link that shows the history and expires on its own.",
      "compartir.antesFicha": "First, the health record",
      "compartir.antesFichaTexto":
        "What gets shown is {nombre}'s health record: allergies, medication and illnesses. Fill it in first and come back here.",
      "compartir.antesFichaTextoSin":
        "What gets shown is your pet's health record: allergies, medication and illnesses. Fill it in first and come back here.",
      "compartir.escribirFicha": "Fill in the health record",
      "compartir.errorCrear": "Couldn't create the link",
      "compartir.retirarPregunta": "Withdraw this link?",
      "compartir.retirarTexto": "It stops opening right away. What someone already saw can't be erased.",
      "compartir.retirarSi": "Yes, withdraw it",
      "compartir.errorRetirar": "Couldn't withdraw it",
      "compartir.qrTitulo": "Show them this QR code",
      "compartir.qrEtiqueta": "QR code for the link to the history",
      "compartir.qrTexto": "The vet scans it with their phone. Valid until {dia} at {hora}.",
      "compartir.lleva": "It includes the health record.",
      "compartir.llevaUno": "It includes the health record and one entry of vaccines, treatments and notes.",
      "compartir.llevaVarios": "It includes the health record and {n} entries of vaccines, treatments and notes.",
      "compartir.guardalo": "Save it now: the key is inside the link itself and can't be shown again.",
      "compartir.enviar": "Send the link",
      "compartir.crearTitulo": "Create a link",
      "compartir.duracion": "How long it's valid",
      "compartir.duracion.24": "24 hours",
      "compartir.duracion.72": "3 days",
      "compartir.duracion.168": "7 days",
      "compartir.crear": "Create the link",
      "compartir.crearTexto":
        "They'll see the health record, the vaccines and treatments on file and notes from past visits, in their language and without creating an account. They can leave you a note from the visit: it reaches your inbox encrypted.",
      "compartir.abiertos": "Links still open",
      "compartir.abiertosTexto": "The ones from this screen and from the travel passport.",
      "compartir.creado": "Created on {fecha}",
      "compartir.valeHasta": "Valid until {dia} at {hora}",
      "compartir.retirar": "Withdraw",
    },
    fr: {
      "compartir.titulo": "Partager avec un vétérinaire",
      "compartir.intro": "Pour une consultation loin de chez vous : un lien qui montre l'historique et expire tout seul.",
      "compartir.antesFicha": "D'abord, la fiche santé",
      "compartir.antesFichaTexto":
        "Ce qui est montré, c'est la fiche de {nombre} : ses allergies, ses traitements et ses maladies. Remplissez-la d'abord, puis revenez ici.",
      "compartir.antesFichaTextoSin":
        "Ce qui est montré, c'est la fiche de votre animal : ses allergies, ses traitements et ses maladies. Remplissez-la d'abord, puis revenez ici.",
      "compartir.escribirFicha": "Remplir la fiche santé",
      "compartir.errorCrear": "Impossible de créer le lien",
      "compartir.retirarPregunta": "Retirer ce lien ?",
      "compartir.retirarTexto": "Il cessera de s'ouvrir immédiatement. Ce que quelqu'un a déjà vu ne peut pas être effacé.",
      "compartir.retirarSi": "Oui, le retirer",
      "compartir.errorRetirar": "Impossible de le retirer",
      "compartir.qrTitulo": "Montrez-lui ce QR code",
      "compartir.qrEtiqueta": "QR code du lien vers l'historique",
      "compartir.qrTexto": "Le vétérinaire le scanne avec son téléphone. Valable jusqu'au {dia} à {hora}.",
      "compartir.lleva": "Il contient la fiche santé.",
      "compartir.llevaUno": "Il contient la fiche santé et un enregistrement de vaccins, traitements et notes.",
      "compartir.llevaVarios": "Il contient la fiche santé et {n} enregistrements de vaccins, traitements et notes.",
      "compartir.guardalo":
        "Gardez-le maintenant : la clé se trouve dans le lien lui-même et ne pourra plus être affichée.",
      "compartir.enviar": "Envoyer le lien",
      "compartir.crearTitulo": "Créer un lien",
      "compartir.duracion": "Durée de validité",
      "compartir.duracion.24": "24 heures",
      "compartir.duracion.72": "3 jours",
      "compartir.duracion.168": "7 jours",
      "compartir.crear": "Créer le lien",
      "compartir.crearTexto":
        "Il verra la fiche santé, les vaccins et traitements enregistrés et les notes des consultations précédentes, dans sa langue et sans créer de compte. Il peut vous laisser la note de la consultation : elle arrive chiffrée dans vos messages.",
      "compartir.abiertos": "Liens encore ouverts",
      "compartir.abiertosTexto": "Ceux de cet écran et ceux du passeport de voyage.",
      "compartir.creado": "Créé le {fecha}",
      "compartir.valeHasta": "Valable jusqu'au {dia} à {hora}",
      "compartir.retirar": "Retirer",
    },
  },
);
