/* Lo que se repite por toda la app: pestañas, títulos de las pantallas de
   una mascota y los botones de siempre. */

import { seccion } from "./seccion";

export default seccion(
  {
    "comun.tab.mascotas": "Mis mascotas",
    "comun.tab.bandeja": "Bandeja",
    "comun.tab.permisos": "Permisos",
    "comun.tab.cuenta": "Cuenta",
    "comun.pantalla.mascota": "Mi mascota",
    "comun.pantalla.salud": "Ficha de salud",
    "comun.pantalla.placa": "Placa del collar",
    "comun.pantalla.compartir": "Compartir",
    "comun.pantalla.perfil": "Perfil público",
    "comun.pantalla.pasaporte": "Pasaporte de viaje",
    "comun.cargando": "Cargando…",
    "comun.cerrar": "Cerrar",
    "comun.cancelar": "Cancelar",
    "comun.volver": "No, volver",
    "comun.siBorrar": "Sí, borrar",
    "comun.borrar": "Borrar",
    "comun.guardar": "Guardar",
    "comun.hecho": "Hecho",
    "comun.reintentar": "Reintentar",
    "comun.tuMascota": "Tu mascota",
    "comun.errorCarga": "No se ha podido cargar. Tira hacia abajo para reintentar.",
    "comun.errorReintentar": "Vuelve a intentarlo en un momento.",
  },
  {
    pt: {
      "comun.tab.mascotas": "Os meus animais",
      "comun.tab.bandeja": "Caixa de entrada",
      "comun.tab.permisos": "Permissões",
      "comun.tab.cuenta": "Conta",
      "comun.pantalla.mascota": "O meu animal",
      "comun.pantalla.salud": "Ficha de saúde",
      "comun.pantalla.placa": "Placa da coleira",
      "comun.pantalla.compartir": "Partilhar",
      "comun.pantalla.perfil": "Perfil público",
      "comun.pantalla.pasaporte": "Passaporte de viagem",
      "comun.cargando": "A carregar…",
      "comun.cerrar": "Fechar",
      "comun.cancelar": "Cancelar",
      "comun.volver": "Não, voltar",
      "comun.siBorrar": "Sim, apagar",
      "comun.borrar": "Apagar",
      "comun.guardar": "Guardar",
      "comun.hecho": "Concluído",
      "comun.reintentar": "Tentar de novo",
      "comun.tuMascota": "O teu animal",
      "comun.errorCarga": "Não foi possível carregar. Puxa para baixo para tentar de novo.",
      "comun.errorReintentar": "Tenta de novo daqui a pouco.",
    },
    en: {
      "comun.tab.mascotas": "My pets",
      "comun.tab.bandeja": "Inbox",
      "comun.tab.permisos": "Permissions",
      "comun.tab.cuenta": "Account",
      "comun.pantalla.mascota": "My pet",
      "comun.pantalla.salud": "Health record",
      "comun.pantalla.placa": "Collar tag",
      "comun.pantalla.compartir": "Share",
      "comun.pantalla.perfil": "Public profile",
      "comun.pantalla.pasaporte": "Travel passport",
      "comun.cargando": "Loading…",
      "comun.cerrar": "Close",
      "comun.cancelar": "Cancel",
      "comun.volver": "No, go back",
      "comun.siBorrar": "Yes, delete",
      "comun.borrar": "Delete",
      "comun.guardar": "Save",
      "comun.hecho": "Done",
      "comun.reintentar": "Try again",
      "comun.tuMascota": "Your pet",
      "comun.errorCarga": "Couldn't load. Pull down to try again.",
      "comun.errorReintentar": "Please try again in a moment.",
    },
    fr: {
      "comun.tab.mascotas": "Mes animaux",
      "comun.tab.bandeja": "Messages",
      "comun.tab.permisos": "Autorisations",
      "comun.tab.cuenta": "Compte",
      "comun.pantalla.mascota": "Mon animal",
      "comun.pantalla.salud": "Fiche santé",
      "comun.pantalla.placa": "Médaille du collier",
      "comun.pantalla.compartir": "Partager",
      "comun.pantalla.perfil": "Profil public",
      "comun.pantalla.pasaporte": "Passeport de voyage",
      "comun.cargando": "Chargement…",
      "comun.cerrar": "Fermer",
      "comun.cancelar": "Annuler",
      "comun.volver": "Non, revenir",
      "comun.siBorrar": "Oui, supprimer",
      "comun.borrar": "Supprimer",
      "comun.guardar": "Enregistrer",
      "comun.hecho": "Terminé",
      "comun.reintentar": "Réessayer",
      "comun.tuMascota": "Votre animal",
      "comun.errorCarga": "Impossible de charger. Tirez vers le bas pour réessayer.",
      "comun.errorReintentar": "Réessayez dans un instant.",
    },
  },
);
