import { seccion } from "./seccion";

export default seccion(
  {
    "cuenta.titulo": "Cuenta",
    "cuenta.correo": "Correo",
    "cuenta.claveSi": "Clave guardada en este móvil",
    "cuenta.claveNo": "Este móvil no tiene tu clave",
    "cuenta.claveSiTexto": "Tu bandeja se abre aquí. La clave vive en el llavero del sistema y no sale del móvil.",
    "cuenta.claveNoTexto": "Sin ella no se pueden abrir los mensajes de la bandeja.",
    "cuenta.escribirCodigo": "Escribir el código",
    "cuenta.avisosSi": "Avisos activados",
    "cuenta.avisosNo": "Avisos sin activar",
    "cuenta.avisosTexto":
      "Te avisamos cuando llega un mensaje o reclaman el chip. El aviso no dice nada del contenido: lo lees al abrir la app.",
    "cuenta.activarAvisos": "Activar avisos",
    "cuenta.motivo.simulador": "Los avisos solo funcionan en un móvil de verdad, no en el simulador.",
    "cuenta.motivo.permiso": "Sin permiso para notificaciones. Actívalo en los ajustes del sistema.",
    "cuenta.motivo.sinProyecto": "Esta compilación no tiene configurados los avisos (falta EAS_PROJECT_ID).",
    "cuenta.motivo.error": "No se ha podido registrar este móvil. Vuelve a intentarlo.",
    "cuenta.pantalla": "Pantalla",
    "cuenta.tema": "Tema",
    "cuenta.tema.sistema": "El del sistema",
    "cuenta.tema.claro": "Claro",
    "cuenta.tema.oscuro": "Oscuro",
    "cuenta.letra": "Tamaño de letra",
    "cuenta.letra.normal": "Normal",
    "cuenta.letra.grande": "Grande",
    "cuenta.letra.muyGrande": "Muy grande",
    "cuenta.idioma": "Idioma",
    "cuenta.idioma.sistema": "El del sistema",
    "cuenta.pantallaNota":
      "Se aplica solo en este móvil. El tamaño se suma al que tengas puesto en los ajustes del sistema.",
    "cuenta.salir": "Salir",
    "cuenta.salirPregunta": "¿Salir de la cuenta?",
    "cuenta.salirTexto": "Este móvil dejará de recibir avisos y olvidará tu clave. El papel la rehace.",
    "cuenta.salirSi": "Sí, salir",
  },
  {
    pt: {
      "cuenta.titulo": "Conta",
      "cuenta.correo": "E-mail",
      "cuenta.claveSi": "Chave guardada neste telemóvel",
      "cuenta.claveNo": "Este telemóvel não tem a tua chave",
      "cuenta.claveSiTexto":
        "A tua caixa de entrada abre-se aqui. A chave fica no porta-chaves do sistema e não sai do telemóvel.",
      "cuenta.claveNoTexto": "Sem ela não é possível abrir as mensagens da caixa de entrada.",
      "cuenta.escribirCodigo": "Escrever o código",
      "cuenta.avisosSi": "Avisos ativados",
      "cuenta.avisosNo": "Avisos por ativar",
      "cuenta.avisosTexto":
        "Avisamos-te quando chega uma mensagem ou reclamam o chip. O aviso não diz nada do conteúdo: lês-lo ao abrir a app.",
      "cuenta.activarAvisos": "Ativar avisos",
      "cuenta.motivo.simulador": "Os avisos só funcionam num telemóvel real, não no simulador.",
      "cuenta.motivo.permiso": "Sem permissão para notificações. Ativa-a nas definições do sistema.",
      "cuenta.motivo.sinProyecto": "Esta compilação não tem os avisos configurados (falta EAS_PROJECT_ID).",
      "cuenta.motivo.error": "Não foi possível registar este telemóvel. Tenta de novo.",
      "cuenta.pantalla": "Ecrã",
      "cuenta.tema": "Tema",
      "cuenta.tema.sistema": "O do sistema",
      "cuenta.tema.claro": "Claro",
      "cuenta.tema.oscuro": "Escuro",
      "cuenta.letra": "Tamanho da letra",
      "cuenta.letra.normal": "Normal",
      "cuenta.letra.grande": "Grande",
      "cuenta.letra.muyGrande": "Muito grande",
      "cuenta.idioma": "Idioma",
      "cuenta.idioma.sistema": "O do sistema",
      "cuenta.pantallaNota": "Aplica-se só neste telemóvel. O tamanho soma-se ao que tiveres nas definições do sistema.",
      "cuenta.salir": "Sair",
      "cuenta.salirPregunta": "Sair da conta?",
      "cuenta.salirTexto": "Este telemóvel deixará de receber avisos e esquecerá a tua chave. O papel recupera-a.",
      "cuenta.salirSi": "Sim, sair",
    },
    en: {
      "cuenta.titulo": "Account",
      "cuenta.correo": "Email",
      "cuenta.claveSi": "Key saved on this phone",
      "cuenta.claveNo": "This phone doesn't have your key",
      "cuenta.claveSiTexto": "Your inbox opens here. The key lives in the system keychain and never leaves the phone.",
      "cuenta.claveNoTexto": "Without it, the messages in your inbox can't be opened.",
      "cuenta.escribirCodigo": "Enter the code",
      "cuenta.avisosSi": "Notifications on",
      "cuenta.avisosNo": "Notifications off",
      "cuenta.avisosTexto":
        "We let you know when a message arrives or someone claims the chip. The notification says nothing about the content: you read it when you open the app.",
      "cuenta.activarAvisos": "Turn on notifications",
      "cuenta.motivo.simulador": "Notifications only work on a real phone, not in the simulator.",
      "cuenta.motivo.permiso": "No permission for notifications. Turn it on in the system settings.",
      "cuenta.motivo.sinProyecto": "This build has no notifications set up (EAS_PROJECT_ID is missing).",
      "cuenta.motivo.error": "Couldn't register this phone. Please try again.",
      "cuenta.pantalla": "Display",
      "cuenta.tema": "Theme",
      "cuenta.tema.sistema": "System",
      "cuenta.tema.claro": "Light",
      "cuenta.tema.oscuro": "Dark",
      "cuenta.letra": "Text size",
      "cuenta.letra.normal": "Normal",
      "cuenta.letra.grande": "Large",
      "cuenta.letra.muyGrande": "Extra large",
      "cuenta.idioma": "Language",
      "cuenta.idioma.sistema": "System",
      "cuenta.pantallaNota": "Applies only on this phone. The size adds to the one set in your system settings.",
      "cuenta.salir": "Log out",
      "cuenta.salirPregunta": "Log out of your account?",
      "cuenta.salirTexto":
        "This phone will stop receiving notifications and will forget your key. Your paper code restores it.",
      "cuenta.salirSi": "Yes, log out",
    },
    fr: {
      "cuenta.titulo": "Compte",
      "cuenta.correo": "E-mail",
      "cuenta.claveSi": "Clé enregistrée sur ce téléphone",
      "cuenta.claveNo": "Ce téléphone n'a pas votre clé",
      "cuenta.claveSiTexto":
        "Vos messages s'ouvrent ici. La clé reste dans le trousseau du système et ne quitte jamais le téléphone.",
      "cuenta.claveNoTexto": "Sans elle, les messages ne peuvent pas être ouverts.",
      "cuenta.escribirCodigo": "Saisir le code",
      "cuenta.avisosSi": "Notifications activées",
      "cuenta.avisosNo": "Notifications désactivées",
      "cuenta.avisosTexto":
        "Nous vous prévenons quand un message arrive ou qu'on réclame la puce. La notification ne dit rien du contenu : vous le lisez en ouvrant l'app.",
      "cuenta.activarAvisos": "Activer les notifications",
      "cuenta.motivo.simulador": "Les notifications ne fonctionnent que sur un vrai téléphone, pas dans le simulateur.",
      "cuenta.motivo.permiso": "Pas d'autorisation pour les notifications. Activez-la dans les réglages du système.",
      "cuenta.motivo.sinProyecto": "Cette version n'a pas de notifications configurées (EAS_PROJECT_ID manquant).",
      "cuenta.motivo.error": "Impossible d'enregistrer ce téléphone. Réessayez.",
      "cuenta.pantalla": "Affichage",
      "cuenta.tema": "Thème",
      "cuenta.tema.sistema": "Celui du système",
      "cuenta.tema.claro": "Clair",
      "cuenta.tema.oscuro": "Sombre",
      "cuenta.letra": "Taille du texte",
      "cuenta.letra.normal": "Normale",
      "cuenta.letra.grande": "Grande",
      "cuenta.letra.muyGrande": "Très grande",
      "cuenta.idioma": "Langue",
      "cuenta.idioma.sistema": "Celle du système",
      "cuenta.pantallaNota":
        "S'applique uniquement sur ce téléphone. La taille s'ajoute à celle définie dans les réglages du système.",
      "cuenta.salir": "Se déconnecter",
      "cuenta.salirPregunta": "Se déconnecter du compte ?",
      "cuenta.salirTexto":
        "Ce téléphone ne recevra plus de notifications et oubliera votre clé. Le code papier permet de la retrouver.",
      "cuenta.salirSi": "Oui, se déconnecter",
    },
  },
);
