import { seccion } from "./seccion";

export default seccion(
  {
    "cuenta.titulo": "Cuenta",
    "cuenta.correo": "Correo",
    "cuenta.claveSi": "Clave guardada en este móvil",
    "cuenta.claveNo": "Este móvil no tiene tu clave",
    "cuenta.claveSiTexto": "Tu bandeja se abre aquí. La clave vive en el llavero del sistema y no sale del móvil.",
    "cuenta.claveNoTexto": "Sin ella no se pueden abrir los mensajes de la bandeja.",
    "cuenta.escribirCodigo": "Escribir el código",
    "cuenta.avisosSi": "Avisos activados",
    "cuenta.avisosNo": "Avisos sin activar",
    "cuenta.avisosTexto":
      "Te avisamos cuando llega un mensaje o reclaman el chip. El aviso no dice nada del contenido: lo lees al abrir la app.",
    "cuenta.activarAvisos": "Activar avisos",
    "cuenta.motivo.simulador": "Los avisos solo funcionan en un móvil de verdad, no en el simulador.",
    "cuenta.motivo.permiso": "Sin permiso para notificaciones. Actívalo en los ajustes del sistema.",
    "cuenta.motivo.sinProyecto": "Esta compilación no tiene configurados los avisos (falta EAS_PROJECT_ID).",
    "cuenta.motivo.error": "No se ha podido registrar este móvil. Vuelve a intentarlo.",
    "cuenta.pantalla": "Pantalla",
    "cuenta.tema": "Tema",
    "cuenta.tema.sistema": "El del sistema",
    "cuenta.tema.claro": "Claro",
    "cuenta.tema.oscuro": "Oscuro",
    "cuenta.letra": "Tamaño de letra",
    "cuenta.letra.normal": "Normal",
    "cuenta.letra.grande": "Grande",
    "cuenta.letra.muyGrande": "Muy grande",
    "cuenta.idioma": "Idioma",
    "cuenta.idioma.sistema": "El del sistema",
    "cuenta.pantallaNota":
      "Se aplica solo en este móvil. El tamaño se suma al que tengas puesto en los ajustes del sistema.",
    "cuenta.salir": "Salir",
    "cuenta.salirPregunta": "¿Salir de la cuenta?",
    "cuenta.salirTexto": "Este móvil dejará de recibir avisos y olvidará tu clave. El papel la rehace.",
    "cuenta.salirSi": "Sí, salir",
    "cuenta.seguridad": "Seguridad",
    "cuenta.contrasena.cambiar": "Cambiar la contraseña",
    "cuenta.contrasena.intro":
      "Al cambiarla se cierran las sesiones abiertas en otros móviles y navegadores. Te avisaremos por correo.",
    "cuenta.contrasena.actual": "Contraseña actual",
    "cuenta.contrasena.nueva": "Contraseña nueva",
    "cuenta.contrasena.repetir": "Repite la contraseña nueva",
    "cuenta.contrasena.corta": "La nueva tiene que tener al menos 12 caracteres.",
    "cuenta.contrasena.distintas": "Las dos contraseñas nuevas no coinciden.",
    "cuenta.contrasena.incorrecta": "La contraseña no es correcta.",
    "cuenta.contrasena.demasiados": "Demasiados intentos. Espera un minuto y vuelve a probar.",
    "cuenta.contrasena.hecho": "Contraseña cambiada",
    "cuenta.contrasena.hechoTexto": "Las demás sesiones se han cerrado.",
    "cuenta.borrar": "Borrar la cuenta",
    "cuenta.borrar.intro":
      "Se borra todo y no se puede deshacer: tus mascotas, sus fichas de salud, placas y pasaportes, la bandeja y los permisos de las clínicas. Las placas del collar dejarán de funcionar y los chips quedarán libres para registrarse de nuevo.",
    "cuenta.borrar.campo": "Escribe tu contraseña para confirmar",
    "cuenta.borrar.boton": "Borrar mi cuenta",
    "cuenta.borrar.pregunta": "¿Borrar la cuenta para siempre?",
    "cuenta.borrar.preguntaTexto": "No hay papelera: no se podrá recuperar nada.",
    "cuenta.borrar.si": "Sí, borrar todo",
  },
  {
    pt: {
      "cuenta.titulo": "Conta",
      "cuenta.correo": "E-mail",
      "cuenta.claveSi": "Chave guardada neste telemóvel",
      "cuenta.claveNo": "Este telemóvel não tem a tua chave",
      "cuenta.claveSiTexto":
        "A tua caixa de entrada abre-se aqui. A chave fica no porta-chaves do sistema e não sai do telemóvel.",
      "cuenta.claveNoTexto": "Sem ela não é possível abrir as mensagens da caixa de entrada.",
      "cuenta.escribirCodigo": "Escrever o código",
      "cuenta.avisosSi": "Avisos ativados",
      "cuenta.avisosNo": "Avisos por ativar",
      "cuenta.avisosTexto":
        "Avisamos-te quando chega uma mensagem ou reclamam o chip. O aviso não diz nada do conteúdo: lês-lo ao abrir a app.",
      "cuenta.activarAvisos": "Ativar avisos",
      "cuenta.motivo.simulador": "Os avisos só funcionam num telemóvel real, não no simulador.",
      "cuenta.motivo.permiso": "Sem permissão para notificações. Ativa-a nas definições do sistema.",
      "cuenta.motivo.sinProyecto": "Esta compilação não tem os avisos configurados (falta EAS_PROJECT_ID).",
      "cuenta.motivo.error": "Não foi possível registar este telemóvel. Tenta de novo.",
      "cuenta.pantalla": "Ecrã",
      "cuenta.tema": "Tema",
      "cuenta.tema.sistema": "O do sistema",
      "cuenta.tema.claro": "Claro",
      "cuenta.tema.oscuro": "Escuro",
      "cuenta.letra": "Tamanho da letra",
      "cuenta.letra.normal": "Normal",
      "cuenta.letra.grande": "Grande",
      "cuenta.letra.muyGrande": "Muito grande",
      "cuenta.idioma": "Idioma",
      "cuenta.idioma.sistema": "O do sistema",
      "cuenta.pantallaNota": "Aplica-se só neste telemóvel. O tamanho soma-se ao que tiveres nas definições do sistema.",
      "cuenta.salir": "Sair",
      "cuenta.salirPregunta": "Sair da conta?",
      "cuenta.salirTexto": "Este telemóvel deixará de receber avisos e esquecerá a tua chave. O papel recupera-a.",
      "cuenta.salirSi": "Sim, sair",
      "cuenta.seguridad": "Segurança",
      "cuenta.contrasena.cambiar": "Mudar a palavra-passe",
      "cuenta.contrasena.intro":
        "Ao mudá-la, fecham-se as sessões abertas noutros telemóveis e navegadores. Vamos avisar-te por e-mail.",
      "cuenta.contrasena.actual": "Palavra-passe atual",
      "cuenta.contrasena.nueva": "Palavra-passe nova",
      "cuenta.contrasena.repetir": "Repete a palavra-passe nova",
      "cuenta.contrasena.corta": "A nova tem de ter pelo menos 12 caracteres.",
      "cuenta.contrasena.distintas": "As duas palavras-passe novas não coincidem.",
      "cuenta.contrasena.incorrecta": "A palavra-passe não está correta.",
      "cuenta.contrasena.demasiados": "Demasiadas tentativas. Espera um minuto e tenta de novo.",
      "cuenta.contrasena.hecho": "Palavra-passe mudada",
      "cuenta.contrasena.hechoTexto": "As outras sessões foram fechadas.",
      "cuenta.borrar": "Apagar a conta",
      "cuenta.borrar.intro":
        "Apaga-se tudo e não é possível desfazer: os teus animais, as fichas de saúde, placas e passaportes, a caixa de entrada e as permissões das clínicas. As placas da coleira deixam de funcionar e os chips ficam livres para serem registados de novo.",
      "cuenta.borrar.campo": "Escreve a tua palavra-passe para confirmar",
      "cuenta.borrar.boton": "Apagar a minha conta",
      "cuenta.borrar.pregunta": "Apagar a conta para sempre?",
      "cuenta.borrar.preguntaTexto": "Não há reciclagem: não será possível recuperar nada.",
      "cuenta.borrar.si": "Sim, apagar tudo",
    },
    en: {
      "cuenta.titulo": "Account",
      "cuenta.correo": "Email",
      "cuenta.claveSi": "Key saved on this phone",
      "cuenta.claveNo": "This phone doesn't have your key",
      "cuenta.claveSiTexto": "Your inbox opens here. The key lives in the system keychain and never leaves the phone.",
      "cuenta.claveNoTexto": "Without it, the messages in your inbox can't be opened.",
      "cuenta.escribirCodigo": "Enter the code",
      "cuenta.avisosSi": "Notifications on",
      "cuenta.avisosNo": "Notifications off",
      "cuenta.avisosTexto":
        "We let you know when a message arrives or someone claims the chip. The notification says nothing about the content: you read it when you open the app.",
      "cuenta.activarAvisos": "Turn on notifications",
      "cuenta.motivo.simulador": "Notifications only work on a real phone, not in the simulator.",
      "cuenta.motivo.permiso": "No permission for notifications. Turn it on in the system settings.",
      "cuenta.motivo.sinProyecto": "This build has no notifications set up (EAS_PROJECT_ID is missing).",
      "cuenta.motivo.error": "Couldn't register this phone. Please try again.",
      "cuenta.pantalla": "Display",
      "cuenta.tema": "Theme",
      "cuenta.tema.sistema": "System",
      "cuenta.tema.claro": "Light",
      "cuenta.tema.oscuro": "Dark",
      "cuenta.letra": "Text size",
      "cuenta.letra.normal": "Normal",
      "cuenta.letra.grande": "Large",
      "cuenta.letra.muyGrande": "Extra large",
      "cuenta.idioma": "Language",
      "cuenta.idioma.sistema": "System",
      "cuenta.pantallaNota": "Applies only on this phone. The size adds to the one set in your system settings.",
      "cuenta.salir": "Log out",
      "cuenta.salirPregunta": "Log out of your account?",
      "cuenta.salirTexto":
        "This phone will stop receiving notifications and will forget your key. Your paper code restores it.",
      "cuenta.salirSi": "Yes, log out",
      "cuenta.seguridad": "Security",
      "cuenta.contrasena.cambiar": "Change password",
      "cuenta.contrasena.intro": "Changing it logs you out on other phones and browsers. We'll let you know by email.",
      "cuenta.contrasena.actual": "Current password",
      "cuenta.contrasena.nueva": "New password",
      "cuenta.contrasena.repetir": "Repeat the new password",
      "cuenta.contrasena.corta": "The new one must be at least 12 characters long.",
      "cuenta.contrasena.distintas": "The two new passwords don't match.",
      "cuenta.contrasena.incorrecta": "The password isn't correct.",
      "cuenta.contrasena.demasiados": "Too many attempts. Wait a minute and try again.",
      "cuenta.contrasena.hecho": "Password changed",
      "cuenta.contrasena.hechoTexto": "Your other sessions have been logged out.",
      "cuenta.borrar": "Delete account",
      "cuenta.borrar.intro":
        "Everything is deleted and it can't be undone: your pets, their health records, tags and passports, your inbox and the clinics' permissions. Collar tags will stop working and the chips will be free to be registered again.",
      "cuenta.borrar.campo": "Enter your password to confirm",
      "cuenta.borrar.boton": "Delete my account",
      "cuenta.borrar.pregunta": "Delete your account for good?",
      "cuenta.borrar.preguntaTexto": "There's no recycle bin: nothing can be recovered.",
      "cuenta.borrar.si": "Yes, delete everything",
    },
    fr: {
      "cuenta.titulo": "Compte",
      "cuenta.correo": "E-mail",
      "cuenta.claveSi": "Clé enregistrée sur ce téléphone",
      "cuenta.claveNo": "Ce téléphone n'a pas votre clé",
      "cuenta.claveSiTexto":
        "Vos messages s'ouvrent ici. La clé reste dans le trousseau du système et ne quitte jamais le téléphone.",
      "cuenta.claveNoTexto": "Sans elle, les messages ne peuvent pas être ouverts.",
      "cuenta.escribirCodigo": "Saisir le code",
      "cuenta.avisosSi": "Notifications activées",
      "cuenta.avisosNo": "Notifications désactivées",
      "cuenta.avisosTexto":
        "Nous vous prévenons quand un message arrive ou qu'on réclame la puce. La notification ne dit rien du contenu : vous le lisez en ouvrant l'app.",
      "cuenta.activarAvisos": "Activer les notifications",
      "cuenta.motivo.simulador": "Les notifications ne fonctionnent que sur un vrai téléphone, pas dans le simulateur.",
      "cuenta.motivo.permiso": "Pas d'autorisation pour les notifications. Activez-la dans les réglages du système.",
      "cuenta.motivo.sinProyecto": "Cette version n'a pas de notifications configurées (EAS_PROJECT_ID manquant).",
      "cuenta.motivo.error": "Impossible d'enregistrer ce téléphone. Réessayez.",
      "cuenta.pantalla": "Affichage",
      "cuenta.tema": "Thème",
      "cuenta.tema.sistema": "Celui du système",
      "cuenta.tema.claro": "Clair",
      "cuenta.tema.oscuro": "Sombre",
      "cuenta.letra": "Taille du texte",
      "cuenta.letra.normal": "Normale",
      "cuenta.letra.grande": "Grande",
      "cuenta.letra.muyGrande": "Très grande",
      "cuenta.idioma": "Langue",
      "cuenta.idioma.sistema": "Celle du système",
      "cuenta.pantallaNota":
        "S'applique uniquement sur ce téléphone. La taille s'ajoute à celle définie dans les réglages du système.",
      "cuenta.salir": "Se déconnecter",
      "cuenta.salirPregunta": "Se déconnecter du compte ?",
      "cuenta.salirTexto":
        "Ce téléphone ne recevra plus de notifications et oubliera votre clé. Le code papier permet de la retrouver.",
      "cuenta.salirSi": "Oui, se déconnecter",
      "cuenta.seguridad": "Sécurité",
      "cuenta.contrasena.cambiar": "Changer le mot de passe",
      "cuenta.contrasena.intro":
        "Le changer ferme les sessions ouvertes sur vos autres téléphones et navigateurs. Nous vous préviendrons par e-mail.",
      "cuenta.contrasena.actual": "Mot de passe actuel",
      "cuenta.contrasena.nueva": "Nouveau mot de passe",
      "cuenta.contrasena.repetir": "Répétez le nouveau mot de passe",
      "cuenta.contrasena.corta": "Le nouveau doit contenir au moins 12 caractères.",
      "cuenta.contrasena.distintas": "Les deux nouveaux mots de passe ne correspondent pas.",
      "cuenta.contrasena.incorrecta": "Le mot de passe n'est pas correct.",
      "cuenta.contrasena.demasiados": "Trop de tentatives. Attendez une minute et réessayez.",
      "cuenta.contrasena.hecho": "Mot de passe changé",
      "cuenta.contrasena.hechoTexto": "Vos autres sessions ont été fermées.",
      "cuenta.borrar": "Supprimer le compte",
      "cuenta.borrar.intro":
        "Tout est supprimé, sans retour possible : vos animaux, leurs fiches santé, médailles et passeports, vos messages et les autorisations des cliniques. Les médailles du collier cesseront de fonctionner et les puces pourront être enregistrées à nouveau.",
      "cuenta.borrar.campo": "Saisissez votre mot de passe pour confirmer",
      "cuenta.borrar.boton": "Supprimer mon compte",
      "cuenta.borrar.pregunta": "Supprimer le compte définitivement ?",
      "cuenta.borrar.preguntaTexto": "Il n'y a pas de corbeille : rien ne pourra être récupéré.",
      "cuenta.borrar.si": "Oui, tout supprimer",
    },
  },
);
