/* Entrar en la app: chip y contraseña, el código que llega por correo o SMS
   y el código de recuperación en papel que rehace la clave en el móvil. */

import { seccion } from "./seccion";

export default seccion(
  {
    "entrada.entrar.titulo": "Entrar",
    "entrada.entrar.intro": "Con el chip de tu mascota y tu contraseña.",
    "entrada.entrar.chip": "Número de chip",
    "entrada.entrar.clave": "Contraseña",
    "entrada.entrar.errorChip": "Escribe los 15 dígitos del chip (o los 9–10 caracteres de un chip antiguo).",
    "entrada.entrar.error401": "El chip o la contraseña no son correctos.",
    "entrada.entrar.error429": "Demasiados intentos seguidos. Espera un minuto y vuelve a probar.",
    "entrada.entrar.errorRed": "Sin conexión. Comprueba la red y vuelve a intentarlo.",
    "entrada.entrar.errorEnvio": "No se ha podido enviar el código. Vuelve a intentarlo en un momento.",
    "entrada.entrar.continuar": "Continuar",
    "entrada.entrar.olvidada": "¿Has olvidado la contraseña?",
    "entrada.entrar.alta":
      "¿Aún no tienes cuenta? Date de alta en barkandmeow.app/mi-mascota: allí se genera el código de recuperación en papel que abre tu bandeja.",
    "entrada.codigo.titulo": "Escribe el código",
    "entrada.codigo.porSms": "Te lo hemos enviado por SMS al",
    "entrada.codigo.porCorreo": "Te lo hemos enviado a",
    "entrada.codigo.caduca": "Caduca en 15 minutos.",
    "entrada.codigo.campo": "Código",
    "entrada.codigo.entrar": "Entrar",
    "entrada.codigo.otro": "Enviar otro código",
    "entrada.codigo.recibirSms": "Recibirlo por SMS",
    "entrada.codigo.recibirCorreo": "Recibirlo por correo",
    "entrada.codigo.volver": "Volver",
    "entrada.codigo.incorrecto": "Código incorrecto.",
    "entrada.codigo.incorrecto.uno": "Código incorrecto. Te queda 1 intento.",
    "entrada.codigo.incorrecto.varios": "Código incorrecto. Te quedan {n} intentos.",
    "entrada.codigo.caducado": "El código ha caducado o se han agotado los intentos. Vuelve a empezar.",
    "entrada.codigo.errorComprobar": "No se ha podido comprobar el código. Vuelve a intentarlo.",
    "entrada.codigo.nuevo": "Te hemos enviado un código nuevo. El anterior ya no vale.",
    "entrada.codigo.espera": "Espera {n} s antes de pedir otro código.",
    "entrada.codigo.sinSms": "Has llegado al límite de SMS de hoy. Pide el código por correo.",
    "entrada.codigo.errorEnvio": "No se ha podido enviar otro código.",
    "entrada.clave.titulo": "Tu código de recuperación",
    "entrada.clave.intro":
      "Son 8 bloques de 4 caracteres que apuntaste en papel al darte de alta. Con él, este móvil puede abrir tu bandeja y la ficha de salud de tus mascotas.",
    "entrada.clave.campo": "Código de recuperación",
    "entrada.clave.invalido": "El código no es válido: revisa cada bloque en el papel.",
    "entrada.clave.otraCuenta": "Ese código es válido, pero no es el de esta cuenta.",
    "entrada.clave.error": "No se ha podido comprobar. Revisa la conexión y vuelve a intentarlo.",
    "entrada.clave.guardar": "Guardar la clave en este móvil",
    "entrada.clave.ahoraNo": "Ahora no",
    "entrada.canalAvisos": "Avisos de Bark & Meow",
  },
  {
    pt: {
      "entrada.entrar.titulo": "Entrar",
      "entrada.entrar.intro": "Com o chip do teu animal e a tua palavra-passe.",
      "entrada.entrar.chip": "Número do chip",
      "entrada.entrar.clave": "Palavra-passe",
      "entrada.entrar.errorChip": "Escreve os 15 dígitos do chip (ou os 9–10 caracteres de um chip antigo).",
      "entrada.entrar.error401": "O chip ou a palavra-passe não estão corretos.",
      "entrada.entrar.error429": "Demasiadas tentativas seguidas. Espera um minuto e tenta outra vez.",
      "entrada.entrar.errorRed": "Sem ligação. Verifica a rede e tenta de novo.",
      "entrada.entrar.errorEnvio": "Não foi possível enviar o código. Tenta de novo daqui a pouco.",
      "entrada.entrar.continuar": "Continuar",
      "entrada.entrar.olvidada": "Esqueceste-te da palavra-passe?",
      "entrada.entrar.alta":
        "Ainda não tens conta? Regista-te em barkandmeow.app/mi-mascota: aí é gerado o código de recuperação em papel que abre a tua caixa de entrada.",
      "entrada.codigo.titulo": "Escreve o código",
      "entrada.codigo.porSms": "Enviámos-to por SMS para o",
      "entrada.codigo.porCorreo": "Enviámos-to para",
      "entrada.codigo.caduca": "Expira em 15 minutos.",
      "entrada.codigo.campo": "Código",
      "entrada.codigo.entrar": "Entrar",
      "entrada.codigo.otro": "Enviar outro código",
      "entrada.codigo.recibirSms": "Receber por SMS",
      "entrada.codigo.recibirCorreo": "Receber por e-mail",
      "entrada.codigo.volver": "Voltar",
      "entrada.codigo.incorrecto": "Código incorreto.",
      "entrada.codigo.incorrecto.uno": "Código incorreto. Resta-te 1 tentativa.",
      "entrada.codigo.incorrecto.varios": "Código incorreto. Restam-te {n} tentativas.",
      "entrada.codigo.caducado": "O código expirou ou esgotaram-se as tentativas. Começa de novo.",
      "entrada.codigo.errorComprobar": "Não foi possível verificar o código. Tenta de novo.",
      "entrada.codigo.nuevo": "Enviámos-te um código novo. O anterior já não é válido.",
      "entrada.codigo.espera": "Espera {n} s antes de pedir outro código.",
      "entrada.codigo.sinSms": "Chegaste ao limite de SMS de hoje. Pede o código por e-mail.",
      "entrada.codigo.errorEnvio": "Não foi possível enviar outro código.",
      "entrada.clave.titulo": "O teu código de recuperação",
      "entrada.clave.intro":
        "São 8 blocos de 4 caracteres que apontaste em papel quando te registaste. Com ele, este telemóvel pode abrir a tua caixa de entrada e a ficha de saúde dos teus animais.",
      "entrada.clave.campo": "Código de recuperação",
      "entrada.clave.invalido": "O código não é válido: revê cada bloco no papel.",
      "entrada.clave.otraCuenta": "Esse código é válido, mas não é o desta conta.",
      "entrada.clave.error": "Não foi possível verificar. Verifica a ligação e tenta de novo.",
      "entrada.clave.guardar": "Guardar a chave neste telemóvel",
      "entrada.clave.ahoraNo": "Agora não",
      "entrada.canalAvisos": "Avisos da Bark & Meow",
    },
    en: {
      "entrada.entrar.titulo": "Log in",
      "entrada.entrar.intro": "With your pet's microchip and your password.",
      "entrada.entrar.chip": "Microchip number",
      "entrada.entrar.clave": "Password",
      "entrada.entrar.errorChip": "Enter the 15 digits of the microchip (or the 9–10 characters of an older one).",
      "entrada.entrar.error401": "The microchip or password is wrong.",
      "entrada.entrar.error429": "Too many attempts in a row. Wait a minute and try again.",
      "entrada.entrar.errorRed": "No connection. Check your network and try again.",
      "entrada.entrar.errorEnvio": "Couldn't send the code. Please try again in a moment.",
      "entrada.entrar.continuar": "Continue",
      "entrada.entrar.olvidada": "Forgot your password?",
      "entrada.entrar.alta":
        "Don't have an account yet? Sign up at barkandmeow.app/mi-mascota: that's where you get the paper recovery code that opens your inbox.",
      "entrada.codigo.titulo": "Enter the code",
      "entrada.codigo.porSms": "We've sent it by SMS to",
      "entrada.codigo.porCorreo": "We've sent it to",
      "entrada.codigo.caduca": "It expires in 15 minutes.",
      "entrada.codigo.campo": "Code",
      "entrada.codigo.entrar": "Log in",
      "entrada.codigo.otro": "Send another code",
      "entrada.codigo.recibirSms": "Get it by SMS",
      "entrada.codigo.recibirCorreo": "Get it by email",
      "entrada.codigo.volver": "Back",
      "entrada.codigo.incorrecto": "Wrong code.",
      "entrada.codigo.incorrecto.uno": "Wrong code. You have 1 attempt left.",
      "entrada.codigo.incorrecto.varios": "Wrong code. You have {n} attempts left.",
      "entrada.codigo.caducado": "The code has expired or you've used up your attempts. Start again.",
      "entrada.codigo.errorComprobar": "Couldn't check the code. Please try again.",
      "entrada.codigo.nuevo": "We've sent you a new code. The previous one no longer works.",
      "entrada.codigo.espera": "Wait {n} s before asking for another code.",
      "entrada.codigo.sinSms": "You've reached today's SMS limit. Ask for the code by email.",
      "entrada.codigo.errorEnvio": "Couldn't send another code.",
      "entrada.clave.titulo": "Your recovery code",
      "entrada.clave.intro":
        "It's 8 blocks of 4 characters that you wrote down on paper when you signed up. With it, this phone can open your inbox and your pets' health records.",
      "entrada.clave.campo": "Recovery code",
      "entrada.clave.invalido": "The code isn't valid: check each block on the paper.",
      "entrada.clave.otraCuenta": "That code is valid, but it's not the one for this account.",
      "entrada.clave.error": "Couldn't check it. Check your connection and try again.",
      "entrada.clave.guardar": "Save the key on this phone",
      "entrada.clave.ahoraNo": "Not now",
      "entrada.canalAvisos": "Bark & Meow notifications",
    },
    fr: {
      "entrada.entrar.titulo": "Se connecter",
      "entrada.entrar.intro": "Avec la micropuce de votre animal et votre mot de passe.",
      "entrada.entrar.chip": "Numéro de micropuce",
      "entrada.entrar.clave": "Mot de passe",
      "entrada.entrar.errorChip":
        "Saisissez les 15 chiffres de la micropuce (ou les 9 à 10 caractères d'une ancienne micropuce).",
      "entrada.entrar.error401": "La micropuce ou le mot de passe est incorrect.",
      "entrada.entrar.error429": "Trop de tentatives d'affilée. Attendez une minute et réessayez.",
      "entrada.entrar.errorRed": "Pas de connexion. Vérifiez le réseau et réessayez.",
      "entrada.entrar.errorEnvio": "Impossible d'envoyer le code. Réessayez dans un instant.",
      "entrada.entrar.continuar": "Continuer",
      "entrada.entrar.olvidada": "Mot de passe oublié ?",
      "entrada.entrar.alta":
        "Pas encore de compte ? Inscrivez-vous sur barkandmeow.app/mi-mascota : c'est là qu'est généré le code de récupération sur papier qui ouvre vos messages.",
      "entrada.codigo.titulo": "Saisissez le code",
      "entrada.codigo.porSms": "Nous vous l'avons envoyé par SMS au",
      "entrada.codigo.porCorreo": "Nous vous l'avons envoyé à",
      "entrada.codigo.caduca": "Il expire dans 15 minutes.",
      "entrada.codigo.campo": "Code",
      "entrada.codigo.entrar": "Se connecter",
      "entrada.codigo.otro": "Envoyer un autre code",
      "entrada.codigo.recibirSms": "Le recevoir par SMS",
      "entrada.codigo.recibirCorreo": "Le recevoir par e-mail",
      "entrada.codigo.volver": "Retour",
      "entrada.codigo.incorrecto": "Code incorrect.",
      "entrada.codigo.incorrecto.uno": "Code incorrect. Il vous reste 1 tentative.",
      "entrada.codigo.incorrecto.varios": "Code incorrect. Il vous reste {n} tentatives.",
      "entrada.codigo.caducado": "Le code a expiré ou les tentatives sont épuisées. Recommencez.",
      "entrada.codigo.errorComprobar": "Impossible de vérifier le code. Réessayez.",
      "entrada.codigo.nuevo": "Nous vous avons envoyé un nouveau code. L'ancien n'est plus valable.",
      "entrada.codigo.espera": "Attendez {n} s avant de demander un autre code.",
      "entrada.codigo.sinSms": "Vous avez atteint la limite de SMS pour aujourd'hui. Demandez le code par e-mail.",
      "entrada.codigo.errorEnvio": "Impossible d'envoyer un autre code.",
      "entrada.clave.titulo": "Votre code de récupération",
      "entrada.clave.intro":
        "Ce sont 8 blocs de 4 caractères que vous avez notés sur papier à l'inscription. Avec lui, ce téléphone peut ouvrir vos messages et la fiche santé de vos animaux.",
      "entrada.clave.campo": "Code de récupération",
      "entrada.clave.invalido": "Le code n'est pas valide : vérifiez chaque bloc sur le papier.",
      "entrada.clave.otraCuenta": "Ce code est valide, mais ce n'est pas celui de ce compte.",
      "entrada.clave.error": "Impossible de vérifier. Vérifiez la connexion et réessayez.",
      "entrada.clave.guardar": "Enregistrer la clé sur ce téléphone",
      "entrada.clave.ahoraNo": "Pas maintenant",
      "entrada.canalAvisos": "Notifications Bark & Meow",
    },
  },
);
