/* Entrar en la app: chip y contraseña, el código que llega por correo o SMS
   y el código de recuperación en papel que rehace la clave en el móvil. Y lo
   que va antes y después: darse de alta y recuperar la contraseña. */

import { seccion } from "./seccion";

export default seccion(
  {
    "entrada.entrar.titulo": "Entrar",
    "entrada.entrar.intro": "Con el chip de tu mascota y tu contraseña.",
    "entrada.entrar.chip": "Número de chip",
    "entrada.entrar.clave": "Contraseña",
    "entrada.entrar.errorChip": "Escribe los 15 dígitos del chip (o los 9–10 caracteres de un chip antiguo).",
    "entrada.entrar.error401": "El chip o la contraseña no son correctos.",
    "entrada.entrar.error429": "Demasiados intentos seguidos. Espera un minuto y vuelve a probar.",
    "entrada.entrar.errorRed": "Sin conexión. Comprueba la red y vuelve a intentarlo.",
    "entrada.entrar.errorEnvio": "No se ha podido enviar el código. Vuelve a intentarlo en un momento.",
    "entrada.entrar.continuar": "Continuar",
    "entrada.entrar.olvidada": "¿Has olvidado la contraseña?",
    "entrada.codigo.titulo": "Escribe el código",
    "entrada.codigo.porSms": "Te lo hemos enviado por SMS al",
    "entrada.codigo.porCorreo": "Te lo hemos enviado a",
    "entrada.codigo.caduca": "Caduca en 15 minutos.",
    "entrada.codigo.campo": "Código",
    "entrada.codigo.entrar": "Entrar",
    "entrada.codigo.otro": "Enviar otro código",
    "entrada.codigo.recibirSms": "Recibirlo por SMS",
    "entrada.codigo.recibirCorreo": "Recibirlo por correo",
    "entrada.codigo.volver": "Volver",
    "entrada.codigo.incorrecto": "Código incorrecto.",
    "entrada.codigo.incorrecto.uno": "Código incorrecto. Te queda 1 intento.",
    "entrada.codigo.incorrecto.varios": "Código incorrecto. Te quedan {n} intentos.",
    "entrada.codigo.caducado": "El código ha caducado o se han agotado los intentos. Vuelve a empezar.",
    "entrada.codigo.errorComprobar": "No se ha podido comprobar el código. Vuelve a intentarlo.",
    "entrada.codigo.nuevo": "Te hemos enviado un código nuevo. El anterior ya no vale.",
    "entrada.codigo.espera": "Espera {n} s antes de pedir otro código.",
    "entrada.codigo.sinSms": "Has llegado al límite de SMS de hoy. Pide el código por correo.",
    "entrada.codigo.errorEnvio": "No se ha podido enviar otro código.",
    "entrada.clave.titulo": "Tu código de recuperación",
    "entrada.clave.intro":
      "Son 8 bloques de 4 caracteres que apuntaste en papel al darte de alta. Con él, este móvil puede abrir tu bandeja y la ficha de salud de tus mascotas.",
    "entrada.clave.campo": "Código de recuperación",
    "entrada.clave.invalido": "El código no es válido: revisa cada bloque en el papel.",
    "entrada.clave.otraCuenta": "Ese código es válido, pero no es el de esta cuenta.",
    "entrada.clave.error": "No se ha podido comprobar. Revisa la conexión y vuelve a intentarlo.",
    "entrada.clave.guardar": "Guardar la clave en este móvil",
    "entrada.clave.ahoraNo": "Ahora no",
    "entrada.entrar.sinCuenta": "¿Aún no tienes cuenta?",
    "entrada.entrar.crear": "Crear una cuenta",
    "entrada.alta.paso.mascota": "Tu mascota",
    "entrada.alta.paso.cuenta": "Tu cuenta",
    "entrada.alta.paso.clave": "Tu clave",
    "entrada.alta.progreso": "Paso {n} de 3 · {nombre}",
    "entrada.alta.titulo.mascota": "¿Cómo se llama y qué chip lleva?",
    "entrada.alta.titulo.cuenta": "Para entrar, tu correo y una contraseña",
    "entrada.alta.titulo.clave": "Apunta tu código de recuperación",
    "entrada.alta.introMascota":
      "El chip son 15 dígitos: está en su pasaporte o en la cartilla de la clínica. Después, una clínica lo activa con el animal delante.",
    "entrada.alta.nombre": "Cómo se llama",
    "entrada.alta.introCuenta":
      "Para entrar necesitarás el número de chip, esta contraseña y un código que te llegará a este correo.",
    "entrada.alta.email": "Correo",
    "entrada.alta.repetida": "Repite la contraseña",
    "entrada.alta.minimo": "Mínimo 12 caracteres.",
    "entrada.alta.errorEmail": "Revisa el correo.",
    "entrada.alta.emailUsado": "Ya hay una cuenta con este correo. Entra con ella para añadir otra mascota.",
    "entrada.alta.noCoinciden": "Las dos contraseñas no coinciden.",
    "entrada.alta.introClave":
      "Es tu clave de dueño: con ella lees las notas que te dejen los veterinarios. Se genera en este móvil y no sale de aquí.",
    "entrada.alta.aviso.titulo": "Apúntalo en papel y guárdalo en casa",
    "entrada.alta.aviso.texto":
      "Solo se enseña ahora. Sin él no podrás recuperar la cuenta si olvidas la contraseña, ni abrir tus mensajes en otro móvil. Nadie más lo tiene, tampoco Bark & Meow.",
    "entrada.alta.codigoLeido": "Código de recuperación: {codigo}",
    "entrada.alta.apuntado": "Lo he apuntado en papel.",
    "entrada.alta.comprobar": "Para comprobarlo, escribe dos bloques",
    "entrada.alta.bloque": "Bloque {n}",
    "entrada.alta.marcaApuntado": "Marca la casilla cuando el código esté apuntado.",
    "entrada.alta.bloquesMal": "Los bloques no coinciden con el código. Revísalos en el papel.",
    "entrada.alta.crear": "Crear la cuenta",
    "entrada.alta.atras": "Atrás",
    "entrada.alta.yaTengo": "Ya tengo cuenta",
    "entrada.alta.errorRed": "Sin conexión. Tu código de recuperación sigue siendo el mismo: vuelve a intentarlo.",
    "entrada.alta.error": "No se ha podido crear la cuenta. Revisa los datos y vuelve a intentarlo.",
    "entrada.alta.creada": "Tu cuenta está creada",
    "entrada.alta.sinCodigo":
      "No hemos podido enviarte el código de confirmación. Entra con el chip y tu contraseña y te enviaremos otro.",
    "entrada.bienvenida.titulo": "Tu cuenta está lista",
    "entrada.bienvenida.texto":
      "Último paso: para que el chip de {nombre} funcione, una clínica tiene que activarlo con el animal delante. Así nadie puede registrar como suyo el chip de una mascota ajena.",
    "entrada.recuperar.titulo": "Recuperar la contraseña",
    "entrada.recuperar.intro":
      "Te pedimos el código de recuperación que apuntaste en el alta y un código que te llega al correo o por SMS. Así, quien consiga entrar en tu correo no puede quedarse con tu cuenta.",
    "entrada.recuperar.papelAyuda": "Los 8 bloques del papel del alta. No sale de este móvil.",
    "entrada.recuperar.volver": "Volver a entrar",
    "entrada.recuperar.sinPapel":
      "¿Has perdido el papel? Sin él no podemos comprobar que la cuenta es tuya. Da de alta de nuevo a tu mascota y pide en una clínica que reclame el chip con ella delante.",
    "entrada.recuperar.papelAjeno": "El código en papel no corresponde a ese chip.",
    "entrada.recuperar.caducada": "La recuperación ha caducado o se ha agotado. Vuelve a empezar.",
    "entrada.recuperar.error": "No se ha podido comprobar. Revisa los datos y vuelve a intentarlo.",
    "entrada.recuperar.revisaCorreo": "Revisa tu correo",
    "entrada.recuperar.revisaMovil": "Revisa tu móvil",
    "entrada.recuperar.nueva": "Contraseña nueva",
    "entrada.recuperar.ochoCaracteres": "El código tiene 8 caracteres.",
    "entrada.recuperar.minimo": "La contraseña nueva necesita al menos 12 caracteres.",
    "entrada.recuperar.guardar": "Guardar la contraseña nueva",
    "entrada.recuperar.hecho.titulo": "Contraseña cambiada",
    "entrada.recuperar.hecho.texto":
      "Hemos cerrado tu sesión en todos los navegadores y en la app. Entra con la contraseña nueva.",
    "entrada.canalAvisos": "Avisos de Bark & Meow",
  },
  {
    pt: {
      "entrada.entrar.titulo": "Entrar",
      "entrada.entrar.intro": "Com o chip do teu animal e a tua palavra-passe.",
      "entrada.entrar.chip": "Número do chip",
      "entrada.entrar.clave": "Palavra-passe",
      "entrada.entrar.errorChip": "Escreve os 15 dígitos do chip (ou os 9–10 caracteres de um chip antigo).",
      "entrada.entrar.error401": "O chip ou a palavra-passe não estão corretos.",
      "entrada.entrar.error429": "Demasiadas tentativas seguidas. Espera um minuto e tenta outra vez.",
      "entrada.entrar.errorRed": "Sem ligação. Verifica a rede e tenta de novo.",
      "entrada.entrar.errorEnvio": "Não foi possível enviar o código. Tenta de novo daqui a pouco.",
      "entrada.entrar.continuar": "Continuar",
      "entrada.entrar.olvidada": "Esqueceste-te da palavra-passe?",
      "entrada.codigo.titulo": "Escreve o código",
      "entrada.codigo.porSms": "Enviámos-to por SMS para o",
      "entrada.codigo.porCorreo": "Enviámos-to para",
      "entrada.codigo.caduca": "Expira em 15 minutos.",
      "entrada.codigo.campo": "Código",
      "entrada.codigo.entrar": "Entrar",
      "entrada.codigo.otro": "Enviar outro código",
      "entrada.codigo.recibirSms": "Receber por SMS",
      "entrada.codigo.recibirCorreo": "Receber por e-mail",
      "entrada.codigo.volver": "Voltar",
      "entrada.codigo.incorrecto": "Código incorreto.",
      "entrada.codigo.incorrecto.uno": "Código incorreto. Resta-te 1 tentativa.",
      "entrada.codigo.incorrecto.varios": "Código incorreto. Restam-te {n} tentativas.",
      "entrada.codigo.caducado": "O código expirou ou esgotaram-se as tentativas. Começa de novo.",
      "entrada.codigo.errorComprobar": "Não foi possível verificar o código. Tenta de novo.",
      "entrada.codigo.nuevo": "Enviámos-te um código novo. O anterior já não é válido.",
      "entrada.codigo.espera": "Espera {n} s antes de pedir outro código.",
      "entrada.codigo.sinSms": "Chegaste ao limite de SMS de hoje. Pede o código por e-mail.",
      "entrada.codigo.errorEnvio": "Não foi possível enviar outro código.",
      "entrada.clave.titulo": "O teu código de recuperação",
      "entrada.clave.intro":
        "São 8 blocos de 4 caracteres que apontaste em papel quando te registaste. Com ele, este telemóvel pode abrir a tua caixa de entrada e a ficha de saúde dos teus animais.",
      "entrada.clave.campo": "Código de recuperação",
      "entrada.clave.invalido": "O código não é válido: revê cada bloco no papel.",
      "entrada.clave.otraCuenta": "Esse código é válido, mas não é o desta conta.",
      "entrada.clave.error": "Não foi possível verificar. Verifica a ligação e tenta de novo.",
      "entrada.clave.guardar": "Guardar a chave neste telemóvel",
      "entrada.clave.ahoraNo": "Agora não",
      "entrada.entrar.sinCuenta": "Ainda não tens conta?",
      "entrada.entrar.crear": "Criar uma conta",
      "entrada.alta.paso.mascota": "O teu animal",
      "entrada.alta.paso.cuenta": "A tua conta",
      "entrada.alta.paso.clave": "A tua chave",
      "entrada.alta.progreso": "Passo {n} de 3 · {nombre}",
      "entrada.alta.titulo.mascota": "Como se chama e que chip tem?",
      "entrada.alta.titulo.cuenta": "Para entrar, o teu e-mail e uma palavra-passe",
      "entrada.alta.titulo.clave": "Aponta o teu código de recuperação",
      "entrada.alta.introMascota":
        "O chip tem 15 dígitos: está no passaporte ou no boletim da clínica. Depois, uma clínica ativa-o com o animal presente.",
      "entrada.alta.nombre": "Como se chama",
      "entrada.alta.introCuenta":
        "Para entrar vais precisar do número do chip, desta palavra-passe e de um código que vai chegar a este e-mail.",
      "entrada.alta.email": "E-mail",
      "entrada.alta.repetida": "Repete a palavra-passe",
      "entrada.alta.minimo": "Mínimo de 12 caracteres.",
      "entrada.alta.errorEmail": "Revê o e-mail.",
      "entrada.alta.emailUsado": "Já existe uma conta com este e-mail. Entra com ela para adicionar outro animal.",
      "entrada.alta.noCoinciden": "As duas palavras-passe não coincidem.",
      "entrada.alta.introClave":
        "É a tua chave de dono: com ela lês as notas que os veterinários te deixam. É gerada neste telemóvel e não sai daqui.",
      "entrada.alta.aviso.titulo": "Aponta-o em papel e guarda-o em casa",
      "entrada.alta.aviso.texto":
        "Só é mostrado agora. Sem ele não vais conseguir recuperar a conta se te esqueceres da palavra-passe, nem abrir as tuas mensagens noutro telemóvel. Mais ninguém o tem, nem a Bark & Meow.",
      "entrada.alta.codigoLeido": "Código de recuperação: {codigo}",
      "entrada.alta.apuntado": "Já o apontei em papel.",
      "entrada.alta.comprobar": "Para confirmar, escreve dois blocos",
      "entrada.alta.bloque": "Bloco {n}",
      "entrada.alta.marcaApuntado": "Marca a caixa quando o código estiver apontado.",
      "entrada.alta.bloquesMal": "Os blocos não coincidem com o código. Revê-os no papel.",
      "entrada.alta.crear": "Criar a conta",
      "entrada.alta.atras": "Voltar",
      "entrada.alta.yaTengo": "Já tenho conta",
      "entrada.alta.errorRed": "Sem ligação. O teu código de recuperação continua a ser o mesmo: tenta de novo.",
      "entrada.alta.error": "Não foi possível criar a conta. Revê os dados e tenta de novo.",
      "entrada.alta.creada": "A tua conta foi criada",
      "entrada.alta.sinCodigo":
        "Não conseguimos enviar-te o código de confirmação. Entra com o chip e a tua palavra-passe e enviamos-te outro.",
      "entrada.bienvenida.titulo": "A tua conta está pronta",
      "entrada.bienvenida.texto":
        "Último passo: para que o chip de {nombre} funcione, uma clínica tem de o ativar com o animal presente. Assim ninguém pode registar como seu o chip de um animal alheio.",
      "entrada.recuperar.titulo": "Recuperar a palavra-passe",
      "entrada.recuperar.intro":
        "Pedimos-te o código de recuperação que apontaste no registo e um código que te chega por e-mail ou SMS. Assim, quem conseguir entrar no teu e-mail não pode ficar com a tua conta.",
      "entrada.recuperar.papelAyuda": "Os 8 blocos do papel do registo. Não sai deste telemóvel.",
      "entrada.recuperar.volver": "Voltar a entrar",
      "entrada.recuperar.sinPapel":
        "Perdeste o papel? Sem ele não conseguimos confirmar que a conta é tua. Regista de novo o teu animal e pede a uma clínica que reclame o chip com ele presente.",
      "entrada.recuperar.papelAjeno": "O código em papel não corresponde a esse chip.",
      "entrada.recuperar.caducada": "A recuperação expirou ou esgotou-se. Começa de novo.",
      "entrada.recuperar.error": "Não foi possível verificar. Revê os dados e tenta de novo.",
      "entrada.recuperar.revisaCorreo": "Vê o teu e-mail",
      "entrada.recuperar.revisaMovil": "Vê o teu telemóvel",
      "entrada.recuperar.nueva": "Palavra-passe nova",
      "entrada.recuperar.ochoCaracteres": "O código tem 8 caracteres.",
      "entrada.recuperar.minimo": "A palavra-passe nova precisa de pelo menos 12 caracteres.",
      "entrada.recuperar.guardar": "Guardar a palavra-passe nova",
      "entrada.recuperar.hecho.titulo": "Palavra-passe alterada",
      "entrada.recuperar.hecho.texto":
        "Terminámos a tua sessão em todos os navegadores e na app. Entra com a palavra-passe nova.",
      "entrada.canalAvisos": "Avisos da Bark & Meow",
    },
    en: {
      "entrada.entrar.titulo": "Log in",
      "entrada.entrar.intro": "With your pet's microchip and your password.",
      "entrada.entrar.chip": "Microchip number",
      "entrada.entrar.clave": "Password",
      "entrada.entrar.errorChip": "Enter the 15 digits of the microchip (or the 9–10 characters of an older one).",
      "entrada.entrar.error401": "The microchip or password is wrong.",
      "entrada.entrar.error429": "Too many attempts in a row. Wait a minute and try again.",
      "entrada.entrar.errorRed": "No connection. Check your network and try again.",
      "entrada.entrar.errorEnvio": "Couldn't send the code. Please try again in a moment.",
      "entrada.entrar.continuar": "Continue",
      "entrada.entrar.olvidada": "Forgot your password?",
      "entrada.codigo.titulo": "Enter the code",
      "entrada.codigo.porSms": "We've sent it by SMS to",
      "entrada.codigo.porCorreo": "We've sent it to",
      "entrada.codigo.caduca": "It expires in 15 minutes.",
      "entrada.codigo.campo": "Code",
      "entrada.codigo.entrar": "Log in",
      "entrada.codigo.otro": "Send another code",
      "entrada.codigo.recibirSms": "Get it by SMS",
      "entrada.codigo.recibirCorreo": "Get it by email",
      "entrada.codigo.volver": "Back",
      "entrada.codigo.incorrecto": "Wrong code.",
      "entrada.codigo.incorrecto.uno": "Wrong code. You have 1 attempt left.",
      "entrada.codigo.incorrecto.varios": "Wrong code. You have {n} attempts left.",
      "entrada.codigo.caducado": "The code has expired or you've used up your attempts. Start again.",
      "entrada.codigo.errorComprobar": "Couldn't check the code. Please try again.",
      "entrada.codigo.nuevo": "We've sent you a new code. The previous one no longer works.",
      "entrada.codigo.espera": "Wait {n} s before asking for another code.",
      "entrada.codigo.sinSms": "You've reached today's SMS limit. Ask for the code by email.",
      "entrada.codigo.errorEnvio": "Couldn't send another code.",
      "entrada.clave.titulo": "Your recovery code",
      "entrada.clave.intro":
        "It's 8 blocks of 4 characters that you wrote down on paper when you signed up. With it, this phone can open your inbox and your pets' health records.",
      "entrada.clave.campo": "Recovery code",
      "entrada.clave.invalido": "The code isn't valid: check each block on the paper.",
      "entrada.clave.otraCuenta": "That code is valid, but it's not the one for this account.",
      "entrada.clave.error": "Couldn't check it. Check your connection and try again.",
      "entrada.clave.guardar": "Save the key on this phone",
      "entrada.clave.ahoraNo": "Not now",
      "entrada.entrar.sinCuenta": "Don't have an account yet?",
      "entrada.entrar.crear": "Create an account",
      "entrada.alta.paso.mascota": "Your pet",
      "entrada.alta.paso.cuenta": "Your account",
      "entrada.alta.paso.clave": "Your key",
      "entrada.alta.progreso": "Step {n} of 3 · {nombre}",
      "entrada.alta.titulo.mascota": "What's its name and microchip?",
      "entrada.alta.titulo.cuenta": "To log in, your email and a password",
      "entrada.alta.titulo.clave": "Write down your recovery code",
      "entrada.alta.introMascota":
        "The microchip has 15 digits: it's in the pet passport or the clinic's records. Afterwards, a clinic activates it with the animal present.",
      "entrada.alta.nombre": "Name",
      "entrada.alta.introCuenta":
        "To log in you'll need the microchip number, this password and a code we'll send to this email.",
      "entrada.alta.email": "Email",
      "entrada.alta.repetida": "Repeat the password",
      "entrada.alta.minimo": "At least 12 characters.",
      "entrada.alta.errorEmail": "Check the email address.",
      "entrada.alta.emailUsado": "There's already an account with this email. Log in with it to add another pet.",
      "entrada.alta.noCoinciden": "The two passwords don't match.",
      "entrada.alta.introClave":
        "It's your owner key: with it you read the notes vets leave you. It's generated on this phone and never leaves it.",
      "entrada.alta.aviso.titulo": "Write it down on paper and keep it at home",
      "entrada.alta.aviso.texto":
        "It's only shown now. Without it you can't recover your account if you forget your password, or open your messages on another phone. Nobody else has it, not even Bark & Meow.",
      "entrada.alta.codigoLeido": "Recovery code: {codigo}",
      "entrada.alta.apuntado": "I've written it down on paper.",
      "entrada.alta.comprobar": "To check, type two blocks",
      "entrada.alta.bloque": "Block {n}",
      "entrada.alta.marcaApuntado": "Tick the box once the code is written down.",
      "entrada.alta.bloquesMal": "The blocks don't match the code. Check them on the paper.",
      "entrada.alta.crear": "Create the account",
      "entrada.alta.atras": "Back",
      "entrada.alta.yaTengo": "I already have an account",
      "entrada.alta.errorRed": "No connection. Your recovery code is still the same: please try again.",
      "entrada.alta.error": "Couldn't create the account. Check the details and try again.",
      "entrada.alta.creada": "Your account has been created",
      "entrada.alta.sinCodigo":
        "We couldn't send you the confirmation code. Log in with the microchip and your password and we'll send you another.",
      "entrada.bienvenida.titulo": "Your account is ready",
      "entrada.bienvenida.texto":
        "Last step: for {nombre}'s microchip to work, a clinic has to activate it with the animal present. That way nobody can register someone else's pet as their own.",
      "entrada.recuperar.titulo": "Recover your password",
      "entrada.recuperar.intro":
        "We ask for the recovery code you wrote down when you signed up and a code we send by email or SMS. That way, someone who gets into your email can't take over your account.",
      "entrada.recuperar.papelAyuda": "The 8 blocks on the paper from sign-up. It never leaves this phone.",
      "entrada.recuperar.volver": "Back to log in",
      "entrada.recuperar.sinPapel":
        "Lost the paper? Without it we can't check that the account is yours. Sign your pet up again and ask a clinic to claim the microchip with the animal present.",
      "entrada.recuperar.papelAjeno": "The paper code doesn't match that microchip.",
      "entrada.recuperar.caducada": "The recovery has expired or run out of attempts. Start again.",
      "entrada.recuperar.error": "Couldn't check it. Check the details and try again.",
      "entrada.recuperar.revisaCorreo": "Check your email",
      "entrada.recuperar.revisaMovil": "Check your phone",
      "entrada.recuperar.nueva": "New password",
      "entrada.recuperar.ochoCaracteres": "The code has 8 characters.",
      "entrada.recuperar.minimo": "The new password needs at least 12 characters.",
      "entrada.recuperar.guardar": "Save the new password",
      "entrada.recuperar.hecho.titulo": "Password changed",
      "entrada.recuperar.hecho.texto":
        "We've logged you out of every browser and the app. Log in with your new password.",
      "entrada.canalAvisos": "Bark & Meow notifications",
    },
    fr: {
      "entrada.entrar.titulo": "Se connecter",
      "entrada.entrar.intro": "Avec la micropuce de votre animal et votre mot de passe.",
      "entrada.entrar.chip": "Numéro de micropuce",
      "entrada.entrar.clave": "Mot de passe",
      "entrada.entrar.errorChip":
        "Saisissez les 15 chiffres de la micropuce (ou les 9 à 10 caractères d'une ancienne micropuce).",
      "entrada.entrar.error401": "La micropuce ou le mot de passe est incorrect.",
      "entrada.entrar.error429": "Trop de tentatives d'affilée. Attendez une minute et réessayez.",
      "entrada.entrar.errorRed": "Pas de connexion. Vérifiez le réseau et réessayez.",
      "entrada.entrar.errorEnvio": "Impossible d'envoyer le code. Réessayez dans un instant.",
      "entrada.entrar.continuar": "Continuer",
      "entrada.entrar.olvidada": "Mot de passe oublié ?",
      "entrada.codigo.titulo": "Saisissez le code",
      "entrada.codigo.porSms": "Nous vous l'avons envoyé par SMS au",
      "entrada.codigo.porCorreo": "Nous vous l'avons envoyé à",
      "entrada.codigo.caduca": "Il expire dans 15 minutes.",
      "entrada.codigo.campo": "Code",
      "entrada.codigo.entrar": "Se connecter",
      "entrada.codigo.otro": "Envoyer un autre code",
      "entrada.codigo.recibirSms": "Le recevoir par SMS",
      "entrada.codigo.recibirCorreo": "Le recevoir par e-mail",
      "entrada.codigo.volver": "Retour",
      "entrada.codigo.incorrecto": "Code incorrect.",
      "entrada.codigo.incorrecto.uno": "Code incorrect. Il vous reste 1 tentative.",
      "entrada.codigo.incorrecto.varios": "Code incorrect. Il vous reste {n} tentatives.",
      "entrada.codigo.caducado": "Le code a expiré ou les tentatives sont épuisées. Recommencez.",
      "entrada.codigo.errorComprobar": "Impossible de vérifier le code. Réessayez.",
      "entrada.codigo.nuevo": "Nous vous avons envoyé un nouveau code. L'ancien n'est plus valable.",
      "entrada.codigo.espera": "Attendez {n} s avant de demander un autre code.",
      "entrada.codigo.sinSms": "Vous avez atteint la limite de SMS pour aujourd'hui. Demandez le code par e-mail.",
      "entrada.codigo.errorEnvio": "Impossible d'envoyer un autre code.",
      "entrada.clave.titulo": "Votre code de récupération",
      "entrada.clave.intro":
        "Ce sont 8 blocs de 4 caractères que vous avez notés sur papier à l'inscription. Avec lui, ce téléphone peut ouvrir vos messages et la fiche santé de vos animaux.",
      "entrada.clave.campo": "Code de récupération",
      "entrada.clave.invalido": "Le code n'est pas valide : vérifiez chaque bloc sur le papier.",
      "entrada.clave.otraCuenta": "Ce code est valide, mais ce n'est pas celui de ce compte.",
      "entrada.clave.error": "Impossible de vérifier. Vérifiez la connexion et réessayez.",
      "entrada.clave.guardar": "Enregistrer la clé sur ce téléphone",
      "entrada.clave.ahoraNo": "Pas maintenant",
      "entrada.entrar.sinCuenta": "Vous n'avez pas encore de compte ?",
      "entrada.entrar.crear": "Créer un compte",
      "entrada.alta.paso.mascota": "Votre animal",
      "entrada.alta.paso.cuenta": "Votre compte",
      "entrada.alta.paso.clave": "Votre clé",
      "entrada.alta.progreso": "Étape {n} sur 3 · {nombre}",
      "entrada.alta.titulo.mascota": "Comment s'appelle-t-il et quelle est sa micropuce ?",
      "entrada.alta.titulo.cuenta": "Pour vous connecter, votre e-mail et un mot de passe",
      "entrada.alta.titulo.clave": "Notez votre code de récupération",
      "entrada.alta.introMascota":
        "La micropuce comporte 15 chiffres : elle figure sur son passeport ou dans le carnet de la clinique. Ensuite, une clinique l'active en présence de l'animal.",
      "entrada.alta.nombre": "Son nom",
      "entrada.alta.introCuenta":
        "Pour vous connecter, il vous faudra le numéro de micropuce, ce mot de passe et un code envoyé à cette adresse e-mail.",
      "entrada.alta.email": "E-mail",
      "entrada.alta.repetida": "Répétez le mot de passe",
      "entrada.alta.minimo": "12 caractères minimum.",
      "entrada.alta.errorEmail": "Vérifiez l'adresse e-mail.",
      "entrada.alta.emailUsado":
        "Un compte existe déjà avec cet e-mail. Connectez-vous avec lui pour ajouter un autre animal.",
      "entrada.alta.noCoinciden": "Les deux mots de passe ne correspondent pas.",
      "entrada.alta.introClave":
        "C'est votre clé de propriétaire : elle vous permet de lire les notes que vous laissent les vétérinaires. Elle est générée sur ce téléphone et n'en sort pas.",
      "entrada.alta.aviso.titulo": "Notez-le sur papier et gardez-le chez vous",
      "entrada.alta.aviso.texto":
        "Il n'est affiché que maintenant. Sans lui, vous ne pourrez ni récupérer votre compte si vous oubliez le mot de passe, ni ouvrir vos messages sur un autre téléphone. Personne d'autre ne l'a, pas même Bark & Meow.",
      "entrada.alta.codigoLeido": "Code de récupération : {codigo}",
      "entrada.alta.apuntado": "Je l'ai noté sur papier.",
      "entrada.alta.comprobar": "Pour vérifier, saisissez deux blocs",
      "entrada.alta.bloque": "Bloc {n}",
      "entrada.alta.marcaApuntado": "Cochez la case une fois le code noté.",
      "entrada.alta.bloquesMal": "Les blocs ne correspondent pas au code. Vérifiez-les sur le papier.",
      "entrada.alta.crear": "Créer le compte",
      "entrada.alta.atras": "Retour",
      "entrada.alta.yaTengo": "J'ai déjà un compte",
      "entrada.alta.errorRed": "Pas de connexion. Votre code de récupération reste le même : réessayez.",
      "entrada.alta.error": "Impossible de créer le compte. Vérifiez les informations et réessayez.",
      "entrada.alta.creada": "Votre compte est créé",
      "entrada.alta.sinCodigo":
        "Nous n'avons pas pu vous envoyer le code de confirmation. Connectez-vous avec la micropuce et votre mot de passe, et nous vous en enverrons un autre.",
      "entrada.bienvenida.titulo": "Votre compte est prêt",
      "entrada.bienvenida.texto":
        "Dernière étape : pour que la micropuce de {nombre} fonctionne, une clinique doit l'activer en présence de l'animal. Ainsi, personne ne peut enregistrer à son nom la micropuce d'un animal qui n'est pas le sien.",
      "entrada.recuperar.titulo": "Récupérer le mot de passe",
      "entrada.recuperar.intro":
        "Nous vous demandons le code de récupération noté à l'inscription et un code envoyé par e-mail ou par SMS. Ainsi, quelqu'un qui accéderait à votre e-mail ne pourrait pas s'emparer de votre compte.",
      "entrada.recuperar.papelAyuda": "Les 8 blocs du papier de l'inscription. Il ne sort pas de ce téléphone.",
      "entrada.recuperar.volver": "Revenir à la connexion",
      "entrada.recuperar.sinPapel":
        "Vous avez perdu le papier ? Sans lui, nous ne pouvons pas vérifier que le compte est le vôtre. Inscrivez à nouveau votre animal et demandez à une clinique de réclamer la micropuce en sa présence.",
      "entrada.recuperar.papelAjeno": "Le code sur papier ne correspond pas à cette micropuce.",
      "entrada.recuperar.caducada": "La récupération a expiré ou les tentatives sont épuisées. Recommencez.",
      "entrada.recuperar.error": "Impossible de vérifier. Vérifiez les informations et réessayez.",
      "entrada.recuperar.revisaCorreo": "Consultez vos e-mails",
      "entrada.recuperar.revisaMovil": "Consultez votre téléphone",
      "entrada.recuperar.nueva": "Nouveau mot de passe",
      "entrada.recuperar.ochoCaracteres": "Le code comporte 8 caractères.",
      "entrada.recuperar.minimo": "Le nouveau mot de passe doit comporter au moins 12 caractères.",
      "entrada.recuperar.guardar": "Enregistrer le nouveau mot de passe",
      "entrada.recuperar.hecho.titulo": "Mot de passe modifié",
      "entrada.recuperar.hecho.texto":
        "Nous vous avons déconnecté de tous les navigateurs et de l'app. Connectez-vous avec le nouveau mot de passe.",
      "entrada.canalAvisos": "Notifications Bark & Meow",
    },
  },
);
