import { seccion } from "./seccion";

export default seccion(
  {
    "mascotas.intro": "Entra en cada una para ver su ficha de salud, su placa y lo que le falta.",
    "mascotas.cargando": "Cargando tus mascotas…",
    "mascotas.vacia": "Tu cuenta aún no tiene ninguna mascota.",
    "mascotas.anadirPrimera": "Añadir tu mascota",
    "mascotas.anadirOtra": "Añadir otra mascota",
    "mascotas.abrir": "Abrir {nombre}",
    "mascotas.mensajes.uno": "1 mensaje en la bandeja",
    "mascotas.mensajes.varios": "{n} mensajes en la bandeja",
    "mascotas.toca.reclamacion": "Hay una reclamación abierta sobre su chip.",
    "mascotas.toca.activar": "Llévala a tu clínica para activar su chip.",
    "mascotas.toca.publicar": "Publica su perfil para que quien la encuentre vea cómo llamarte.",
    "mascotas.toca.telefono": "Añade un teléfono de contacto.",
    "mascotas.toca.ficha": "Escribe su ficha de salud: alergias, medicación y enfermedades.",
    "mascotas.toca.placa": "Prepara la placa de su collar.",
    "mascotas.nueva.otraMas": "Añadir otra",
    "mascotas.nueva.intro": "Con el número de su microchip: son 15 cifras y vienen en su pasaporte.",
    "mascotas.nueva.chip": "Número del microchip",
    "mascotas.nueva.nombre": "Cómo se llama",
    "mascotas.nueva.boton": "Añadir mascota",
    "mascotas.nueva.errorChip": "Un microchip ISO tiene 15 dígitos.",
    "mascotas.nueva.error": "No se ha podido añadir. Revisa el número y vuelve a intentarlo.",
  },
  {
    pt: {
      "mascotas.intro": "Entra em cada um para veres a ficha de saúde, a placa e o que lhe falta.",
      "mascotas.cargando": "A carregar os teus animais…",
      "mascotas.vacia": "A tua conta ainda não tem nenhum animal.",
      "mascotas.anadirPrimera": "Adicionar o teu animal",
      "mascotas.anadirOtra": "Adicionar outro animal",
      "mascotas.abrir": "Abrir {nombre}",
      "mascotas.mensajes.uno": "1 mensagem na caixa de entrada",
      "mascotas.mensajes.varios": "{n} mensagens na caixa de entrada",
      "mascotas.toca.reclamacion": "Há uma reclamação aberta sobre o chip.",
      "mascotas.toca.activar": "Leva-o à tua clínica para ativar o chip.",
      "mascotas.toca.publicar": "Publica o perfil para que quem o encontrar veja como te contactar.",
      "mascotas.toca.telefono": "Adiciona um telefone de contacto.",
      "mascotas.toca.ficha": "Escreve a ficha de saúde: alergias, medicação e doenças.",
      "mascotas.toca.placa": "Prepara a placa da coleira.",
      "mascotas.nueva.otraMas": "Adicionar outro",
      "mascotas.nueva.intro": "Com o número do microchip: são 15 algarismos e vêm no passaporte.",
      "mascotas.nueva.chip": "Número do microchip",
      "mascotas.nueva.nombre": "Como se chama",
      "mascotas.nueva.boton": "Adicionar animal",
      "mascotas.nueva.errorChip": "Um microchip ISO tem 15 algarismos.",
      "mascotas.nueva.error": "Não foi possível adicionar. Verifica o número e tenta de novo.",
    },
    en: {
      "mascotas.intro": "Open each one to see its health record, its tag and what's still missing.",
      "mascotas.cargando": "Loading your pets…",
      "mascotas.vacia": "Your account doesn't have any pets yet.",
      "mascotas.anadirPrimera": "Add your pet",
      "mascotas.anadirOtra": "Add another pet",
      "mascotas.abrir": "Open {nombre}",
      "mascotas.mensajes.uno": "1 message in your inbox",
      "mascotas.mensajes.varios": "{n} messages in your inbox",
      "mascotas.toca.reclamacion": "There's an open claim on its chip.",
      "mascotas.toca.activar": "Take it to your clinic to activate its chip.",
      "mascotas.toca.publicar": "Publish its profile so whoever finds it can see how to reach you.",
      "mascotas.toca.telefono": "Add a contact phone number.",
      "mascotas.toca.ficha": "Fill in its health record: allergies, medication and illnesses.",
      "mascotas.toca.placa": "Set up its collar tag.",
      "mascotas.nueva.otraMas": "Add another",
      "mascotas.nueva.intro": "With its microchip number: it has 15 digits and you'll find it in its passport.",
      "mascotas.nueva.chip": "Microchip number",
      "mascotas.nueva.nombre": "What's its name",
      "mascotas.nueva.boton": "Add pet",
      "mascotas.nueva.errorChip": "An ISO microchip has 15 digits.",
      "mascotas.nueva.error": "Couldn't add it. Check the number and try again.",
    },
    fr: {
      "mascotas.intro": "Ouvrez chacun pour voir sa fiche santé, sa médaille et ce qui lui manque.",
      "mascotas.cargando": "Chargement de vos animaux…",
      "mascotas.vacia": "Votre compte n'a encore aucun animal.",
      "mascotas.anadirPrimera": "Ajouter votre animal",
      "mascotas.anadirOtra": "Ajouter un autre animal",
      "mascotas.abrir": "Ouvrir {nombre}",
      "mascotas.mensajes.uno": "1 message reçu",
      "mascotas.mensajes.varios": "{n} messages reçus",
      "mascotas.toca.reclamacion": "Une réclamation est en cours sur sa puce.",
      "mascotas.toca.activar": "Emmenez-le à votre clinique pour activer sa puce.",
      "mascotas.toca.publicar": "Publiez son profil pour que la personne qui le trouve sache comment vous joindre.",
      "mascotas.toca.telefono": "Ajoutez un numéro de téléphone de contact.",
      "mascotas.toca.ficha": "Remplissez sa fiche santé : allergies, traitements et maladies.",
      "mascotas.toca.placa": "Préparez la médaille de son collier.",
      "mascotas.nueva.otraMas": "Ajouter un autre",
      "mascotas.nueva.intro": "Avec le numéro de sa puce : 15 chiffres, indiqués dans son passeport.",
      "mascotas.nueva.chip": "Numéro de la puce",
      "mascotas.nueva.nombre": "Son nom",
      "mascotas.nueva.boton": "Ajouter l'animal",
      "mascotas.nueva.errorChip": "Une puce ISO comporte 15 chiffres.",
      "mascotas.nueva.error": "Impossible de l'ajouter. Vérifiez le numéro et réessayez.",
    },
  },
);
