/* El resumen de una mascota: qué está hecho y qué falta, y la reclamación
   del chip si la hay. `mascota.tuMascota` va en mitad de una frase, cuando la
   mascota aún no tiene nombre; las frases están escritas para que encaje. */

import { seccion } from "./seccion";

export default seccion(
  {
    "mascota.tuMascota": "tu mascota",
    "mascota.reclamante": "Has reclamado este chip, que estaba activo a nombre de otra persona.",
    "mascota.reclamanteAbierta": "Si no lo impugna, pasará a ti el {fecha}.",
    "mascota.reclamanteImpugnada":
      "La otra persona la ha impugnado: revisaremos el caso con la documentación de las dos partes.",
    "mascota.impugnada":
      "Has impugnado la reclamación. El chip no cambiará de dueño mientras revisamos el caso; te escribiremos para pedirte la documentación.",
    "mascota.impugnarPregunta": "¿Impugnar la reclamación sobre {nombre}?",
    "mascota.impugnarTexto":
      "El chip no cambiará de dueño y revisaremos el caso a mano con la documentación de las dos partes.",
    "mascota.impugnarSi": "Sí, impugnar",
    "mascota.impugnarError": "No se ha podido impugnar",
    "mascota.impugnarErrorTexto": "Vuelve a intentarlo en un momento o entra en el portal web.",
    "mascota.reclamadoTitulo": "Alguien ha reclamado este chip",
    "mascota.reclamadoTexto":
      "Una clínica ha registrado que otra persona dice ser la dueña de {nombre} y ha llevado un animal con este chip. Si no haces nada, el chip pasará a esa persona el {fecha}. Mientras tanto, tu perfil público no se muestra.",
    "mascota.impugnarBoton": "Impugnar: el animal es mío",
    "mascota.codigoError": "No se ha podido generar el código",
    "mascota.generarCodigo": "Generar código de activación",
    "mascota.mensajes.uno": "1 mensaje en la bandeja",
    "mascota.mensajes.varios": "{n} mensajes en la bandeja",
    "mascota.siLePasa": "Si le pasa algo",
    "mascota.fichaHecha": "Ficha de salud escrita",
    "mascota.fichaHechaTexto": "Alergias, medicación y enfermedades. Tenla al día.",
    "mascota.fichaFaltaTexto":
      "Si tiene alguna alergia o toma medicación, un veterinario de urgencias no lo sabrá. Son cinco minutos.",
    "mascota.verFicha": "Ver la ficha de salud",
    "mascota.escribirFicha": "Escribir la ficha de salud",
    "mascota.placaActiva": "Placa del collar activa",
    "mascota.placaActivaTexto": "Quien la escanee ve el resumen de urgencia, en su idioma.",
    "mascota.placaFaltaTexto": "Un QR en el collar que abre el resumen de urgencia en cualquier móvil.",
    "mascota.verPlaca": "Ver la placa",
    "mascota.prepararPlaca": "Preparar la placa",
    "mascota.ensenarHistorial": "Enseñar el historial a un veterinario",
    "mascota.siSePierde": "Si se pierde",
    "mascota.chipActivado": "Chip activado en una clínica",
    "mascota.chipPendiente":
      "Una clínica tiene que leerlo con tu mascota delante. Genera el código cuando vayas a ir: el anterior, si lo había, deja de valer.",
    "mascota.chipDesde": "Desde el {fecha}",
    "mascota.perfilVisible": "Perfil público visible",
    "mascota.perfilOculto": "Quien la encuentre no verá su nombre ni tu teléfono.",
    "mascota.telefono": "Un teléfono para llamarte",
    "mascota.editarPerfil": "Editar el perfil público",
    "mascota.fotoWeb": "La foto se sube desde barkandmeow.app/mi-mascota.",
    "mascota.paraViajar": "Para viajar",
    "mascota.viajarTexto": "Qué pide cada destino, qué consta ya y un QR para enseñarlo en la frontera.",
    "mascota.clinica": "Tu clínica de siempre",
    "mascota.permisosTexto": "Quién tiene acceso permanente a la ficha, y cómo retirarlo.",
    "mascota.abrir": "Abrir",
  },
  {
    pt: {
      "mascota.tuMascota": "o teu animal",
      "mascota.reclamante": "Reclamaste este chip, que estava ativo em nome de outra pessoa.",
      "mascota.reclamanteAbierta": "Se essa pessoa não contestar, passa para ti em {fecha}.",
      "mascota.reclamanteImpugnada":
        "A outra pessoa contestou: vamos rever o caso com a documentação das duas partes.",
      "mascota.impugnada":
        "Contestaste a reclamação. O chip não muda de dono enquanto revemos o caso; vamos escrever-te a pedir a documentação.",
      "mascota.impugnarPregunta": "Contestar a reclamação sobre {nombre}?",
      "mascota.impugnarTexto":
        "O chip não muda de dono e vamos rever o caso à mão com a documentação das duas partes.",
      "mascota.impugnarSi": "Sim, contestar",
      "mascota.impugnarError": "Não foi possível contestar",
      "mascota.impugnarErrorTexto": "Tenta de novo daqui a pouco ou entra no portal web.",
      "mascota.reclamadoTitulo": "Alguém reclamou este chip",
      "mascota.reclamadoTexto":
        "Uma clínica registou que outra pessoa afirma que {nombre} lhe pertence e levou um animal com este chip. Se não fizeres nada, o chip passa para essa pessoa em {fecha}. Entretanto, o teu perfil público não é mostrado.",
      "mascota.impugnarBoton": "Contestar: o animal é meu",
      "mascota.codigoError": "Não foi possível gerar o código",
      "mascota.generarCodigo": "Gerar código de ativação",
      "mascota.mensajes.uno": "1 mensagem na caixa de entrada",
      "mascota.mensajes.varios": "{n} mensagens na caixa de entrada",
      "mascota.siLePasa": "Se lhe acontecer alguma coisa",
      "mascota.fichaHecha": "Ficha de saúde preenchida",
      "mascota.fichaHechaTexto": "Alergias, medicação e doenças. Mantém-na em dia.",
      "mascota.fichaFaltaTexto":
        "Se tiver alguma alergia ou tomar medicação, um veterinário de urgência não vai saber. São cinco minutos.",
      "mascota.verFicha": "Ver a ficha de saúde",
      "mascota.escribirFicha": "Preencher a ficha de saúde",
      "mascota.placaActiva": "Placa da coleira ativa",
      "mascota.placaActivaTexto": "Quem a ler vê o resumo de urgência, no seu idioma.",
      "mascota.placaFaltaTexto": "Um QR na coleira que abre o resumo de urgência em qualquer telemóvel.",
      "mascota.verPlaca": "Ver a placa",
      "mascota.prepararPlaca": "Preparar a placa",
      "mascota.ensenarHistorial": "Mostrar o histórico a um veterinário",
      "mascota.siSePierde": "Se se perder",
      "mascota.chipActivado": "Chip ativado numa clínica",
      "mascota.chipPendiente":
        "Uma clínica tem de o ler com o teu animal presente. Gera o código quando fores lá: o anterior, se havia, deixa de valer.",
      "mascota.chipDesde": "Desde {fecha}",
      "mascota.perfilVisible": "Perfil público visível",
      "mascota.perfilOculto": "Quem o encontrar não verá o nome dele nem o teu telefone.",
      "mascota.telefono": "Um telefone para te ligarem",
      "mascota.editarPerfil": "Editar o perfil público",
      "mascota.fotoWeb": "A fotografia carrega-se em barkandmeow.app/mi-mascota.",
      "mascota.paraViajar": "Para viajar",
      "mascota.viajarTexto": "O que pede cada destino, o que já consta e um QR para mostrar na fronteira.",
      "mascota.clinica": "A tua clínica de sempre",
      "mascota.permisosTexto": "Quem tem acesso permanente à ficha, e como retirá-lo.",
      "mascota.abrir": "Abrir",
    },
    en: {
      "mascota.tuMascota": "your pet",
      "mascota.reclamante": "You've claimed this chip, which was active under someone else's name.",
      "mascota.reclamanteAbierta": "If they don't dispute it, it will pass to you on {fecha}.",
      "mascota.reclamanteImpugnada":
        "The other person has disputed it: we'll review the case with documents from both sides.",
      "mascota.impugnada":
        "You've disputed the claim. The chip won't change owner while we review the case; we'll write to you to ask for documents.",
      "mascota.impugnarPregunta": "Dispute the claim on {nombre}?",
      "mascota.impugnarTexto":
        "The chip won't change owner and we'll review the case by hand with documents from both sides.",
      "mascota.impugnarSi": "Yes, dispute",
      "mascota.impugnarError": "Couldn't dispute the claim",
      "mascota.impugnarErrorTexto": "Please try again in a moment or go to the web portal.",
      "mascota.reclamadoTitulo": "Someone has claimed this chip",
      "mascota.reclamadoTexto":
        "A clinic has recorded that another person says they own {nombre} and brought in an animal with this chip. If you do nothing, the chip will pass to that person on {fecha}. In the meantime, your public profile isn't shown.",
      "mascota.impugnarBoton": "Dispute: this animal is mine",
      "mascota.codigoError": "Couldn't generate the code",
      "mascota.generarCodigo": "Generate activation code",
      "mascota.mensajes.uno": "1 message in your inbox",
      "mascota.mensajes.varios": "{n} messages in your inbox",
      "mascota.siLePasa": "If something happens",
      "mascota.fichaHecha": "Health record filled in",
      "mascota.fichaHechaTexto": "Allergies, medication and conditions. Keep it up to date.",
      "mascota.fichaFaltaTexto":
        "If your pet has an allergy or takes medication, an emergency vet won't know. It takes five minutes.",
      "mascota.verFicha": "View the health record",
      "mascota.escribirFicha": "Fill in the health record",
      "mascota.placaActiva": "Collar tag active",
      "mascota.placaActivaTexto": "Whoever scans it sees the emergency summary, in their own language.",
      "mascota.placaFaltaTexto": "A QR code on the collar that opens the emergency summary on any phone.",
      "mascota.verPlaca": "View the tag",
      "mascota.prepararPlaca": "Set up the tag",
      "mascota.ensenarHistorial": "Show the history to a vet",
      "mascota.siSePierde": "If they get lost",
      "mascota.chipActivado": "Chip activated at a clinic",
      "mascota.chipPendiente":
        "A clinic has to scan it with your pet there. Generate the code when you're about to go: the previous one, if any, stops working.",
      "mascota.chipDesde": "Since {fecha}",
      "mascota.perfilVisible": "Public profile visible",
      "mascota.perfilOculto": "Whoever finds your pet won't see its name or your phone number.",
      "mascota.telefono": "A phone number to call you",
      "mascota.editarPerfil": "Edit the public profile",
      "mascota.fotoWeb": "The photo is uploaded at barkandmeow.app/mi-mascota.",
      "mascota.paraViajar": "Travelling",
      "mascota.viajarTexto":
        "What each destination requires, what's already on record and a QR code to show at the border.",
      "mascota.clinica": "Your regular clinic",
      "mascota.permisosTexto": "Who has permanent access to the record, and how to remove it.",
      "mascota.abrir": "Open",
    },
    fr: {
      "mascota.tuMascota": "votre animal",
      "mascota.reclamante": "Vous avez réclamé cette puce, qui était active au nom d'une autre personne.",
      "mascota.reclamanteAbierta": "Si cette personne ne conteste pas, elle vous sera transférée le {fecha}.",
      "mascota.reclamanteImpugnada":
        "L'autre personne a contesté : nous examinerons le dossier avec les documents des deux parties.",
      "mascota.impugnada":
        "Vous avez contesté la réclamation. La puce ne changera pas de propriétaire pendant l'examen du dossier ; nous vous écrirons pour vous demander les documents.",
      "mascota.impugnarPregunta": "Contester la réclamation concernant {nombre} ?",
      "mascota.impugnarTexto":
        "La puce ne changera pas de propriétaire et nous examinerons le dossier nous-mêmes avec les documents des deux parties.",
      "mascota.impugnarSi": "Oui, contester",
      "mascota.impugnarError": "Impossible de contester",
      "mascota.impugnarErrorTexto": "Réessayez dans un instant ou passez par le portail web.",
      "mascota.reclamadoTitulo": "Quelqu'un a réclamé cette puce",
      "mascota.reclamadoTexto":
        "Une clinique a enregistré qu'une autre personne dit être propriétaire de {nombre} et a présenté un animal portant cette puce. Si vous ne faites rien, la puce passera à cette personne le {fecha}. En attendant, votre profil public n'est pas affiché.",
      "mascota.impugnarBoton": "Contester : cet animal est à moi",
      "mascota.codigoError": "Impossible de générer le code",
      "mascota.generarCodigo": "Générer un code d'activation",
      "mascota.mensajes.uno": "1 message reçu",
      "mascota.mensajes.varios": "{n} messages reçus",
      "mascota.siLePasa": "S'il lui arrive quelque chose",
      "mascota.fichaHecha": "Fiche santé remplie",
      "mascota.fichaHechaTexto": "Allergies, traitements et maladies. Tenez-la à jour.",
      "mascota.fichaFaltaTexto":
        "S'il a une allergie ou prend un traitement, un vétérinaire d'urgence ne le saura pas. Cela prend cinq minutes.",
      "mascota.verFicha": "Voir la fiche santé",
      "mascota.escribirFicha": "Remplir la fiche santé",
      "mascota.placaActiva": "Médaille du collier active",
      "mascota.placaActivaTexto": "Qui la scanne voit le résumé d'urgence, dans sa langue.",
      "mascota.placaFaltaTexto":
        "Un QR code sur le collier qui ouvre le résumé d'urgence sur n'importe quel téléphone.",
      "mascota.verPlaca": "Voir la médaille",
      "mascota.prepararPlaca": "Préparer la médaille",
      "mascota.ensenarHistorial": "Montrer l'historique à un vétérinaire",
      "mascota.siSePierde": "S'il se perd",
      "mascota.chipActivado": "Puce activée dans une clinique",
      "mascota.chipPendiente":
        "Une clinique doit la lire en présence de votre animal. Générez le code au moment d'y aller : le précédent, s'il y en avait un, ne sera plus valable.",
      "mascota.chipDesde": "Depuis le {fecha}",
      "mascota.perfilVisible": "Profil public visible",
      "mascota.perfilOculto": "Qui le trouve ne verra ni son nom ni votre téléphone.",
      "mascota.telefono": "Un numéro pour vous appeler",
      "mascota.editarPerfil": "Modifier le profil public",
      "mascota.fotoWeb": "La photo s'ajoute depuis barkandmeow.app/mi-mascota.",
      "mascota.paraViajar": "Pour voyager",
      "mascota.viajarTexto":
        "Ce que demande chaque destination, ce qui est déjà enregistré et un QR code à montrer à la frontière.",
      "mascota.clinica": "Votre clinique habituelle",
      "mascota.permisosTexto": "Qui a un accès permanent à la fiche, et comment le retirer.",
      "mascota.abrir": "Ouvrir",
    },
  },
);
