/* Perfil público: lo que ve quien encuentra al animal. El título de la
   pantalla es comun.pantalla.perfil. */

import { seccion } from "./seccion";

export default seccion(
  {
    "perfil.intro":
      "Lo que verá quien encuentre a tu mascota: al escanear su placa, al consultar su chip en una clínica y dentro de su ficha. La foto se sube desde barkandmeow.app/mi-mascota.",
    "perfil.publicarSi": "Sí, publicarlo",
    "perfil.publicarNo": "No, todavía no",
    "perfil.errorGuardar": "No se ha guardado",
    "perfil.revisaTelefonos": "Revisa los teléfonos.",
    "perfil.revisaConexion": "Revisa la conexión y vuelve a intentarlo.",
    "perfil.datos": "Datos",
    "perfil.nombre": "Cómo se llama",
    "perfil.bio": "Para quien la encuentre ({n}/600)",
    "perfil.bioPista": "Cómo es, qué collar lleva, si se asusta…",
    "perfil.telefonos": "Teléfonos de contacto",
    "perfil.telefonosTexto": "Hasta tres. Se muestran a quien encuentre a tu mascota.",
    "perfil.telefono": "Teléfono {n}",
    "perfil.telefonoMal": "No parece un teléfono: solo cifras, espacios y +.",
    "perfil.deQuien": "De quién es (opcional)",
    "perfil.deQuienPista": "Móvil de Ana, casa…",
    "perfil.quitarTelefono": "Quitar este teléfono",
    "perfil.otroTelefono": "Añadir otro teléfono",
    "perfil.publicar": "Publicarlo",
    "perfil.queLoVea": "Que lo vea quien encuentre a {nombre}",
    "perfil.queLoVeaSin": "Que lo vea quien encuentre a tu mascota",
    "perfil.faltaTelefono": "Para publicarlo hace falta al menos un teléfono: es lo que permite que te llamen.",
  },
  {
    pt: {
      "perfil.intro":
        "O que vê quem encontrar o teu animal: ao ler a placa, ao consultar o chip numa clínica e dentro da ficha. A foto carrega-se em barkandmeow.app/mi-mascota.",
      "perfil.publicarSi": "Sim, publicar",
      "perfil.publicarNo": "Não, ainda não",
      "perfil.errorGuardar": "Não foi guardado",
      "perfil.revisaTelefonos": "Revê os telefones.",
      "perfil.revisaConexion": "Verifica a ligação à internet e tenta de novo.",
      "perfil.datos": "Dados",
      "perfil.nombre": "Como se chama",
      "perfil.bio": "Para quem o encontrar ({n}/600)",
      "perfil.bioPista": "Como é, que coleira usa, se se assusta…",
      "perfil.telefonos": "Telefones de contacto",
      "perfil.telefonosTexto": "Até três. São mostrados a quem encontrar o teu animal.",
      "perfil.telefono": "Telefone {n}",
      "perfil.telefonoMal": "Não parece um telefone: só algarismos, espaços e +.",
      "perfil.deQuien": "De quem é (opcional)",
      "perfil.deQuienPista": "Telemóvel da Ana, casa…",
      "perfil.quitarTelefono": "Remover este telefone",
      "perfil.otroTelefono": "Adicionar outro telefone",
      "perfil.publicar": "Publicar",
      "perfil.queLoVea": "Que o veja quem encontrar {nombre}",
      "perfil.queLoVeaSin": "Que o veja quem encontrar o teu animal",
      "perfil.faltaTelefono": "Para publicar é preciso pelo menos um telefone: é o que permite que te liguem.",
    },
    en: {
      "perfil.intro":
        "What whoever finds your pet will see: when they scan the tag, when a clinic looks up the chip, and inside the health record. The photo is uploaded at barkandmeow.app/mi-mascota.",
      "perfil.publicarSi": "Yes, publish it",
      "perfil.publicarNo": "No, not yet",
      "perfil.errorGuardar": "Not saved",
      "perfil.revisaTelefonos": "Check the phone numbers.",
      "perfil.revisaConexion": "Check your connection and try again.",
      "perfil.datos": "Details",
      "perfil.nombre": "Name",
      "perfil.bio": "For whoever finds them ({n}/600)",
      "perfil.bioPista": "What they look like, which collar they wear, if they get scared…",
      "perfil.telefonos": "Contact phone numbers",
      "perfil.telefonosTexto": "Up to three. They're shown to whoever finds your pet.",
      "perfil.telefono": "Phone {n}",
      "perfil.telefonoMal": "That doesn't look like a phone number: only digits, spaces and +.",
      "perfil.deQuien": "Whose is it (optional)",
      "perfil.deQuienPista": "Ana's mobile, home…",
      "perfil.quitarTelefono": "Remove this phone",
      "perfil.otroTelefono": "Add another phone",
      "perfil.publicar": "Publish",
      "perfil.queLoVea": "Let whoever finds {nombre} see it",
      "perfil.queLoVeaSin": "Let whoever finds your pet see it",
      "perfil.faltaTelefono": "To publish it you need at least one phone number: that's how they can call you.",
    },
    fr: {
      "perfil.intro":
        "Ce que verra la personne qui trouve votre animal : en scannant sa médaille, en consultant sa puce dans une clinique et dans sa fiche. La photo s'ajoute depuis barkandmeow.app/mi-mascota.",
      "perfil.publicarSi": "Oui, le publier",
      "perfil.publicarNo": "Non, pas encore",
      "perfil.errorGuardar": "Non enregistré",
      "perfil.revisaTelefonos": "Vérifiez les numéros de téléphone.",
      "perfil.revisaConexion": "Vérifiez votre connexion et réessayez.",
      "perfil.datos": "Informations",
      "perfil.nombre": "Son nom",
      "perfil.bio": "Pour la personne qui le trouve ({n}/600)",
      "perfil.bioPista": "À quoi il ressemble, quel collier il porte, s'il a peur…",
      "perfil.telefonos": "Téléphones de contact",
      "perfil.telefonosTexto": "Jusqu'à trois. Ils sont montrés à la personne qui trouve votre animal.",
      "perfil.telefono": "Téléphone {n}",
      "perfil.telefonoMal": "Ça ne ressemble pas à un numéro : uniquement des chiffres, des espaces et +.",
      "perfil.deQuien": "À qui est-il (facultatif)",
      "perfil.deQuienPista": "Portable d'Ana, maison…",
      "perfil.quitarTelefono": "Retirer ce téléphone",
      "perfil.otroTelefono": "Ajouter un autre téléphone",
      "perfil.publicar": "Le publier",
      "perfil.queLoVea": "Visible par la personne qui trouve {nombre}",
      "perfil.queLoVeaSin": "Visible par la personne qui trouve votre animal",
      "perfil.faltaTelefono": "Pour le publier, il faut au moins un téléphone : c'est ce qui permet de vous appeler.",
    },
  },
);
