import { seccion } from "./seccion";

export default seccion(
  {
    "permisos.cargando": "Cargando tus permisos…",
    "permisos.errorCarga": "No se han podido cargar los permisos. Tira hacia abajo para reintentar.",
    "permisos.peticiones": "Peticiones que esperan tu respuesta",
    "permisos.sinPeticiones":
      "No hay ninguna. Cuando una clínica pida el alta con tu mascota delante, aparecerá aquí durante diez minutos. Tira hacia abajo para actualizar.",
    "permisos.faltaClave": "Para aprobar hace falta. Escribe el código de recuperación que apuntaste en el alta.",
    "permisos.cabecera": "{pais} · {dominio} · CADUCA {hora}",
    "permisos.sinDominio": "sin dominio propio",
    "permisos.pide": "Pide acceso permanente a la ficha de {nombre}.",
    "permisos.pideNumero": "Pídeles que te digan el número de su pantalla. Si no es este, rechaza la petición.",
    "permisos.coincide": "El número coincide: aprobar",
    "permisos.rechazar": "Rechazar",
    "permisos.conAcceso": "Clínicas con acceso",
    "permisos.sinAcceso": "Ninguna clínica tiene acceso permanente a tus mascotas.",
    "permisos.fichaDesde": "Ficha de {nombre} · desde el {fecha}",
    "permisos.retirar": "Retirar el acceso",
    "permisos.concedido": "Acceso concedido",
    "permisos.concedidoTexto": "{clinica} ya tiene permiso sobre la ficha de {nombre}.",
    "permisos.caducada": "La petición ha caducado",
    "permisos.caducadaTexto": "Pide a la clínica que la repita.",
    "permisos.errorAprobar": "No se ha podido aprobar",
    "permisos.errorRechazar": "No se ha podido rechazar",
    "permisos.errorRechazarTexto": "Puede que ya hubiera caducado.",
    "permisos.errorRetirar": "No se ha podido retirar",
    "permisos.aprobarPregunta": "¿Dar acceso a {clinica}?",
    "permisos.aprobarTexto":
      "Solo si el número que te dicen es {numero}. Podrás retirar el permiso cuando quieras, pero lo que la clínica ya haya descargado no vuelve.",
    "permisos.siCoincide": "Sí, coincide",
    "permisos.retirarPregunta": "¿Retirar el acceso de {clinica}?",
    "permisos.retirarTexto": "Deja de poder enviarte informes y de ver la ficha desde ahora. Lo que ya descargó no vuelve.",
    "permisos.siRetirar": "Sí, retirar",
  },
  {
    pt: {
      "permisos.cargando": "A carregar as tuas permissões…",
      "permisos.errorCarga": "Não foi possível carregar as permissões. Puxa para baixo para tentar de novo.",
      "permisos.peticiones": "Pedidos à espera da tua resposta",
      "permisos.sinPeticiones":
        "Não há nenhum. Quando uma clínica pedir o registo com o teu animal à frente, aparece aqui durante dez minutos. Puxa para baixo para atualizar.",
      "permisos.faltaClave": "É precisa para aprovar. Escreve o código de recuperação que apontaste no registo.",
      "permisos.cabecera": "{pais} · {dominio} · EXPIRA {hora}",
      "permisos.sinDominio": "sem domínio próprio",
      "permisos.pide": "Pede acesso permanente à ficha de {nombre}.",
      "permisos.pideNumero": "Pede-lhes que te digam o número que aparece no ecrã deles. Se não for este, recusa o pedido.",
      "permisos.coincide": "O número coincide: aprovar",
      "permisos.rechazar": "Recusar",
      "permisos.conAcceso": "Clínicas com acesso",
      "permisos.sinAcceso": "Nenhuma clínica tem acesso permanente aos teus animais.",
      "permisos.fichaDesde": "Ficha de {nombre} · desde {fecha}",
      "permisos.retirar": "Retirar o acesso",
      "permisos.concedido": "Acesso concedido",
      "permisos.concedidoTexto": "{clinica} já tem permissão sobre a ficha de {nombre}.",
      "permisos.caducada": "O pedido expirou",
      "permisos.caducadaTexto": "Pede à clínica que o repita.",
      "permisos.errorAprobar": "Não foi possível aprovar",
      "permisos.errorRechazar": "Não foi possível recusar",
      "permisos.errorRechazarTexto": "Talvez já tivesse expirado.",
      "permisos.errorRetirar": "Não foi possível retirar",
      "permisos.aprobarPregunta": "Dar acesso a {clinica}?",
      "permisos.aprobarTexto":
        "Só se o número que te disserem for {numero}. Podes retirar a permissão quando quiseres, mas o que a clínica já tiver descarregado não volta.",
      "permisos.siCoincide": "Sim, coincide",
      "permisos.retirarPregunta": "Retirar o acesso de {clinica}?",
      "permisos.retirarTexto":
        "A partir de agora deixa de poder enviar-te relatórios e de ver a ficha. O que já descarregou não volta.",
      "permisos.siRetirar": "Sim, retirar",
    },
    en: {
      "permisos.cargando": "Loading your permissions…",
      "permisos.errorCarga": "Couldn't load your permissions. Pull down to try again.",
      "permisos.peticiones": "Requests waiting for your answer",
      "permisos.sinPeticiones":
        "There aren't any. When a clinic asks to sign up with your pet in front of them, the request shows up here for ten minutes. Pull down to refresh.",
      "permisos.faltaClave": "You need it to approve. Enter the recovery code you wrote down when you signed up.",
      "permisos.cabecera": "{pais} · {dominio} · EXPIRES {hora}",
      "permisos.sinDominio": "no own domain",
      "permisos.pide": "Asks for permanent access to {nombre}'s record.",
      "permisos.pideNumero": "Ask them to read you the number on their screen. If it isn't this one, decline the request.",
      "permisos.coincide": "The number matches: approve",
      "permisos.rechazar": "Decline",
      "permisos.conAcceso": "Clinics with access",
      "permisos.sinAcceso": "No clinic has permanent access to your pets.",
      "permisos.fichaDesde": "{nombre}'s record · since {fecha}",
      "permisos.retirar": "Remove access",
      "permisos.concedido": "Access granted",
      "permisos.concedidoTexto": "{clinica} now has permission to use {nombre}'s record.",
      "permisos.caducada": "The request has expired",
      "permisos.caducadaTexto": "Ask the clinic to send it again.",
      "permisos.errorAprobar": "Couldn't approve",
      "permisos.errorRechazar": "Couldn't decline",
      "permisos.errorRechazarTexto": "It may have already expired.",
      "permisos.errorRetirar": "Couldn't remove access",
      "permisos.aprobarPregunta": "Give {clinica} access?",
      "permisos.aprobarTexto":
        "Only if the number they tell you is {numero}. You can remove the permission whenever you like, but anything the clinic has already downloaded stays with them.",
      "permisos.siCoincide": "Yes, it matches",
      "permisos.retirarPregunta": "Remove {clinica}'s access?",
      "permisos.retirarTexto":
        "From now on it can't send you reports or see the record. Anything it already downloaded stays with it.",
      "permisos.siRetirar": "Yes, remove",
    },
    fr: {
      "permisos.cargando": "Chargement de vos autorisations…",
      "permisos.errorCarga": "Impossible de charger les autorisations. Tirez vers le bas pour réessayer.",
      "permisos.peticiones": "Demandes en attente de votre réponse",
      "permisos.sinPeticiones":
        "Aucune pour l'instant. Quand une clinique demande l'inscription avec votre animal devant elle, la demande apparaît ici pendant dix minutes. Tirez vers le bas pour actualiser.",
      "permisos.faltaClave":
        "Elle est nécessaire pour approuver. Saisissez le code de récupération noté lors de l'inscription.",
      "permisos.cabecera": "{pais} · {dominio} · EXPIRE À {hora}",
      "permisos.sinDominio": "sans domaine propre",
      "permisos.pide": "Demande un accès permanent à la fiche de {nombre}.",
      "permisos.pideNumero":
        "Demandez-leur le numéro affiché sur leur écran. Si ce n'est pas celui-ci, refusez la demande.",
      "permisos.coincide": "Le numéro correspond : approuver",
      "permisos.rechazar": "Refuser",
      "permisos.conAcceso": "Cliniques ayant accès",
      "permisos.sinAcceso": "Aucune clinique n'a d'accès permanent à vos animaux.",
      "permisos.fichaDesde": "Fiche de {nombre} · depuis le {fecha}",
      "permisos.retirar": "Retirer l'accès",
      "permisos.concedido": "Accès accordé",
      "permisos.concedidoTexto": "{clinica} a désormais accès à la fiche de {nombre}.",
      "permisos.caducada": "La demande a expiré",
      "permisos.caducadaTexto": "Demandez à la clinique de la refaire.",
      "permisos.errorAprobar": "Impossible d'approuver",
      "permisos.errorRechazar": "Impossible de refuser",
      "permisos.errorRechazarTexto": "Elle avait peut-être déjà expiré.",
      "permisos.errorRetirar": "Impossible de retirer l'accès",
      "permisos.aprobarPregunta": "Donner l'accès à {clinica} ?",
      "permisos.aprobarTexto":
        "Seulement si le numéro qu'on vous donne est {numero}. Vous pourrez retirer l'autorisation quand vous voudrez, mais ce que la clinique a déjà téléchargé reste chez elle.",
      "permisos.siCoincide": "Oui, il correspond",
      "permisos.retirarPregunta": "Retirer l'accès de {clinica} ?",
      "permisos.retirarTexto":
        "Dès maintenant, elle ne peut plus vous envoyer de comptes rendus ni voir la fiche. Ce qu'elle a déjà téléchargé reste chez elle.",
      "permisos.siRetirar": "Oui, retirer",
    },
  },
);
