/* La ficha de salud: lo que un veterinario que no conoce al animal necesita
   saber. Las reacciones y las enfermedades del catálogo vienen ya traducidas
   de @barkandmeow/schema; aquí va el resto de la pantalla. */

import { seccion } from "./seccion";

export default seccion(
  {
    "salud.intro":
      "Lo que un veterinario que no conoce a tu mascota necesita saber antes de darle nada. Se guarda cifrada con tu clave: nadie la ve hasta que tú la enseñes.",
    "salud.basico": "Lo básico",
    "salud.especie": "Especie",
    "salud.especie.dog": "Perro",
    "salud.especie.cat": "Gato",
    "salud.especie.ferret": "Hurón",
    "salud.especie.rabbit": "Conejo",
    "salud.especie.bird": "Ave",
    "salud.especie.rodent": "Roedor",
    "salud.especie.reptile": "Reptil",
    "salud.sexo": "Sexo",
    "salud.sexo.hembra": "Hembra",
    "salud.sexo.macho": "Macho",
    "salud.si": "Sí",
    "salud.no": "No",
    "salud.esterilizado": "Esterilizado",
    "salud.esterilizada": "Esterilizada",
    "salud.esterilizacion": "Esterilización",
    "salud.raza": "Raza",
    "salud.razaEjemplo": "Mestiza, labrador…",
    "salud.nacimiento": "Fecha de nacimiento",
    "salud.nacimientoEdad": "Fecha de nacimiento · {edad}",
    "salud.edad.menosMes": "menos de 1 mes",
    "salud.edad.mes.uno": "1 mes",
    "salud.edad.mes.varios": "{n} meses",
    "salud.edad.ano.uno": "1 año",
    "salud.edad.ano.varios": "{n} años",
    "salud.peso": "Peso, en kilos",
    "salud.pesoEjemplo": "12,4",
    "salud.chip": "Número completo del chip (opcional, acaba en {pista})",
    "salud.error.sexo": "Marca si es hembra o macho: sin eso la ficha no se puede enseñar.",
    "salud.error.nacimiento": "La fecha de nacimiento, así: 14/05/2021.",
    "salud.error.futura": "La fecha de nacimiento no puede ser futura.",
    "salud.error.peso": "El peso, en kilos: por ejemplo 12,4.",
    "salud.error.chip": "El número de chip no tiene ese formato.",
    "salud.error.chipPista": "Ese número no acaba en {pista}, como el chip de esta mascota. Revísalo.",
    "salud.alergias": "Alergias",
    "salud.alergiasDe": "ALERGIAS DE {nombre}",
    "salud.ningunaRegistrada": "Ninguna registrada.",
    "salud.quitar": "Quitar",
    "salud.alergiaA": "Alergia a (principio activo o alimento, no la marca)",
    "salud.alergiaEjemplo": "Amoxicilina, pollo…",
    "salud.reaccion": "Qué le pasa",
    "salud.reaccionOtra": "Otra cosa",
    "salud.reaccionTexto": "Descríbelo (se enseña sin traducir)",
    "salud.gravedad": "Gravedad",
    "salud.gravedad.alta": "Grave",
    "salud.gravedad.media": "Moderada",
    "salud.gravedad.baja": "Leve",
    "salud.anadirAlergia": "Añadir alergia",
    "salud.error.sustancia": "Escribe a qué tiene alergia: un medicamento o un alimento.",
    "salud.error.reaccion": "Describe la reacción en pocas palabras.",
    "salud.error.muchasAlergias": "Hay demasiadas alergias apuntadas. Quita alguna.",
    "salud.medicacion": "Medicación habitual",
    "salud.sinMedicacion": "No toma nada de forma habitual.",
    "salud.principio": "Qué toma (el principio activo, no la marca)",
    "salud.principioEjemplo": "Omeprazol",
    "salud.dosis": "Dosis",
    "salud.cada": "Cada cuánto",
    "salud.cada.8": "Cada 8 h",
    "salud.cada.12": "Cada 12 h",
    "salud.cada.24": "Una vez al día",
    "salud.cada.48": "Cada 2 días",
    "salud.cada.168": "Cada semana",
    "salud.cada.720": "Cada mes",
    "salud.cada.horas": "cada {n} horas",
    "salud.anadirMedicamento": "Añadir medicamento",
    "salud.error.principio": "Escribe qué toma.",
    "salud.error.muchosMedicamentos": "Hay demasiados medicamentos apuntados. Quita alguno.",
    "salud.cronicas": "Enfermedades crónicas",
    "salud.cronicaOtra": "Otra",
    "salud.cronicaAnadir": "Añadir una (solo las que haya diagnosticado un veterinario)",
    "salud.cronicaTexto": "Cuál (se enseña sin traducir)",
    "salud.anadirEnfermedad": "Añadir enfermedad",
    "salud.error.elegir": "Elige una de la lista.",
    "salud.error.cual": "Escribe cuál.",
    "salud.error.muchasCronicas": "Hay demasiadas apuntadas. Quita alguna.",
    "salud.rabia": "Vacuna de la rabia",
    "salud.rabiaHasta": "Válida hasta (la fecha de su cartilla)",
    "salud.rabiaCaducada": "Según esta fecha, la vacuna caducó el {fecha}. Si ya se la han puesto, actualízala.",
    "salud.guardarFecha": "Guardar la fecha",
    "salud.error.rabia": "La fecha, así: 14/03/2027. Déjala vacía si no consta.",
    "salud.guardada": "Guardada por última vez el {fecha}.",
    "salud.declarado":
      "Lo que escribes aquí sale marcado como «declarado por el dueño»: no pesa lo mismo que un informe firmado por una clínica.",
    "salud.placaSinActualizar": "La placa no se ha actualizado",
    "salud.placaSinActualizarTexto": "La ficha se ha guardado. La placa se actualizará la próxima vez que guardes.",
    "salud.noGuardada": "No se ha podido guardar",
    "salud.noGuardadaTexto": "Revisa la conexión y vuelve a intentarlo.",
  },
  {
    pt: {
      "salud.intro":
        "O que um veterinário que não conhece o teu animal precisa de saber antes de lhe dar seja o que for. Fica guardada cifrada com a tua chave: ninguém a vê até tu a mostrares.",
      "salud.basico": "O essencial",
      "salud.especie": "Espécie",
      "salud.especie.dog": "Cão",
      "salud.especie.cat": "Gato",
      "salud.especie.ferret": "Furão",
      "salud.especie.rabbit": "Coelho",
      "salud.especie.bird": "Ave",
      "salud.especie.rodent": "Roedor",
      "salud.especie.reptile": "Réptil",
      "salud.sexo": "Sexo",
      "salud.sexo.hembra": "Fêmea",
      "salud.sexo.macho": "Macho",
      "salud.si": "Sim",
      "salud.no": "Não",
      "salud.esterilizado": "Esterilizado",
      "salud.esterilizada": "Esterilizada",
      "salud.esterilizacion": "Esterilização",
      "salud.raza": "Raça",
      "salud.razaEjemplo": "Sem raça definida, labrador…",
      "salud.nacimiento": "Data de nascimento",
      "salud.nacimientoEdad": "Data de nascimento · {edad}",
      "salud.edad.menosMes": "menos de 1 mês",
      "salud.edad.mes.uno": "1 mês",
      "salud.edad.mes.varios": "{n} meses",
      "salud.edad.ano.uno": "1 ano",
      "salud.edad.ano.varios": "{n} anos",
      "salud.peso": "Peso, em quilos",
      "salud.pesoEjemplo": "12,4",
      "salud.chip": "Número completo do chip (opcional, termina em {pista})",
      "salud.error.sexo": "Indica se é fêmea ou macho: sem isso a ficha não pode ser mostrada.",
      "salud.error.nacimiento": "A data de nascimento, assim: 14/05/2021.",
      "salud.error.futura": "A data de nascimento não pode ser no futuro.",
      "salud.error.peso": "O peso, em quilos: por exemplo 12,4.",
      "salud.error.chip": "O número do chip não tem esse formato.",
      "salud.error.chipPista": "Esse número não termina em {pista}, como o chip deste animal. Confirma-o.",
      "salud.alergias": "Alergias",
      "salud.alergiasDe": "ALERGIAS — {nombre}",
      "salud.ningunaRegistrada": "Nenhuma registada.",
      "salud.quitar": "Retirar",
      "salud.alergiaA": "Alergia a (substância ativa ou alimento, não a marca)",
      "salud.alergiaEjemplo": "Amoxicilina, frango…",
      "salud.reaccion": "O que lhe acontece",
      "salud.reaccionOtra": "Outra coisa",
      "salud.reaccionTexto": "Descreve-o (é mostrado sem tradução)",
      "salud.gravedad": "Gravidade",
      "salud.gravedad.alta": "Grave",
      "salud.gravedad.media": "Moderada",
      "salud.gravedad.baja": "Ligeira",
      "salud.anadirAlergia": "Adicionar alergia",
      "salud.error.sustancia": "Escreve a que tem alergia: um medicamento ou um alimento.",
      "salud.error.reaccion": "Descreve a reação em poucas palavras.",
      "salud.error.muchasAlergias": "Há demasiadas alergias registadas. Retira alguma.",
      "salud.medicacion": "Medicação habitual",
      "salud.sinMedicacion": "Não toma nada de forma habitual.",
      "salud.principio": "O que toma (a substância ativa, não a marca)",
      "salud.principioEjemplo": "Omeprazol",
      "salud.dosis": "Dose",
      "salud.cada": "Com que frequência",
      "salud.cada.8": "De 8 em 8 h",
      "salud.cada.12": "De 12 em 12 h",
      "salud.cada.24": "Uma vez por dia",
      "salud.cada.48": "De 2 em 2 dias",
      "salud.cada.168": "Uma vez por semana",
      "salud.cada.720": "Uma vez por mês",
      "salud.cada.horas": "a cada {n} horas",
      "salud.anadirMedicamento": "Adicionar medicamento",
      "salud.error.principio": "Escreve o que toma.",
      "salud.error.muchosMedicamentos": "Há demasiados medicamentos registados. Retira algum.",
      "salud.cronicas": "Doenças crónicas",
      "salud.cronicaOtra": "Outra",
      "salud.cronicaAnadir": "Adicionar uma (só as diagnosticadas por um veterinário)",
      "salud.cronicaTexto": "Qual (é mostrada sem tradução)",
      "salud.anadirEnfermedad": "Adicionar doença",
      "salud.error.elegir": "Escolhe uma da lista.",
      "salud.error.cual": "Escreve qual.",
      "salud.error.muchasCronicas": "Há demasiadas registadas. Retira alguma.",
      "salud.rabia": "Vacina antirrábica",
      "salud.rabiaHasta": "Válida até (a data do boletim de vacinas)",
      "salud.rabiaCaducada": "Segundo esta data, a vacina caducou em {fecha}. Se já foi revacinado, atualiza-a.",
      "salud.guardarFecha": "Guardar a data",
      "salud.error.rabia": "A data, assim: 14/03/2027. Deixa-a vazia se não constar.",
      "salud.guardada": "Guardada pela última vez em {fecha}.",
      "salud.declarado":
        "O que escreves aqui aparece marcado como «declarado pelo tutor»: não tem o mesmo peso que um relatório assinado por uma clínica.",
      "salud.placaSinActualizar": "A placa não foi atualizada",
      "salud.placaSinActualizarTexto": "A ficha foi guardada. A placa será atualizada da próxima vez que guardares.",
      "salud.noGuardada": "Não foi possível guardar",
      "salud.noGuardadaTexto": "Verifica a ligação e tenta de novo.",
    },
    en: {
      "salud.intro":
        "What a vet who doesn't know your pet needs to know before giving it anything. It's saved encrypted with your key: nobody sees it until you show it.",
      "salud.basico": "The basics",
      "salud.especie": "Species",
      "salud.especie.dog": "Dog",
      "salud.especie.cat": "Cat",
      "salud.especie.ferret": "Ferret",
      "salud.especie.rabbit": "Rabbit",
      "salud.especie.bird": "Bird",
      "salud.especie.rodent": "Rodent",
      "salud.especie.reptile": "Reptile",
      "salud.sexo": "Sex",
      "salud.sexo.hembra": "Female",
      "salud.sexo.macho": "Male",
      "salud.si": "Yes",
      "salud.no": "No",
      "salud.esterilizado": "Neutered",
      "salud.esterilizada": "Spayed",
      "salud.esterilizacion": "Neutered or spayed",
      "salud.raza": "Breed",
      "salud.razaEjemplo": "Mixed breed, labrador…",
      "salud.nacimiento": "Date of birth",
      "salud.nacimientoEdad": "Date of birth · {edad}",
      "salud.edad.menosMes": "under 1 month",
      "salud.edad.mes.uno": "1 month",
      "salud.edad.mes.varios": "{n} months",
      "salud.edad.ano.uno": "1 year",
      "salud.edad.ano.varios": "{n} years",
      "salud.peso": "Weight, in kilos",
      "salud.pesoEjemplo": "12.4",
      "salud.chip": "Full microchip number (optional, ends in {pista})",
      "salud.error.sexo": "Choose female or male: without it the record can't be shown.",
      "salud.error.nacimiento": "Date of birth, like this: 14/05/2021.",
      "salud.error.futura": "The date of birth can't be in the future.",
      "salud.error.peso": "Weight in kilos: for example 12.4.",
      "salud.error.chip": "That microchip number isn't in the right format.",
      "salud.error.chipPista": "That number doesn't end in {pista}, like this pet's chip. Please check it.",
      "salud.alergias": "Allergies",
      "salud.alergiasDe": "{nombre}'S ALLERGIES",
      "salud.ningunaRegistrada": "None recorded.",
      "salud.quitar": "Remove",
      "salud.alergiaA": "Allergic to (active ingredient or food, not the brand)",
      "salud.alergiaEjemplo": "Amoxicillin, chicken…",
      "salud.reaccion": "What happens",
      "salud.reaccionOtra": "Something else",
      "salud.reaccionTexto": "Describe it (shown untranslated)",
      "salud.gravedad": "Severity",
      "salud.gravedad.alta": "Severe",
      "salud.gravedad.media": "Moderate",
      "salud.gravedad.baja": "Mild",
      "salud.anadirAlergia": "Add allergy",
      "salud.error.sustancia": "Write what your pet is allergic to: a medicine or a food.",
      "salud.error.reaccion": "Describe the reaction in a few words.",
      "salud.error.muchasAlergias": "There are too many allergies listed. Remove one.",
      "salud.medicacion": "Regular medication",
      "salud.sinMedicacion": "Doesn't take anything regularly.",
      "salud.principio": "What it takes (the active ingredient, not the brand)",
      "salud.principioEjemplo": "Omeprazole",
      "salud.dosis": "Dose",
      "salud.cada": "How often",
      "salud.cada.8": "Every 8 h",
      "salud.cada.12": "Every 12 h",
      "salud.cada.24": "Once a day",
      "salud.cada.48": "Every 2 days",
      "salud.cada.168": "Once a week",
      "salud.cada.720": "Once a month",
      "salud.cada.horas": "every {n} hours",
      "salud.anadirMedicamento": "Add medication",
      "salud.error.principio": "Write what it takes.",
      "salud.error.muchosMedicamentos": "There are too many medications listed. Remove one.",
      "salud.cronicas": "Chronic conditions",
      "salud.cronicaOtra": "Other",
      "salud.cronicaAnadir": "Add one (only those diagnosed by a vet)",
      "salud.cronicaTexto": "Which one (shown untranslated)",
      "salud.anadirEnfermedad": "Add condition",
      "salud.error.elegir": "Choose one from the list.",
      "salud.error.cual": "Write which one.",
      "salud.error.muchasCronicas": "There are too many listed. Remove one.",
      "salud.rabia": "Rabies vaccination",
      "salud.rabiaHasta": "Valid until (the date in its vaccination record)",
      "salud.rabiaCaducada":
        "According to this date, the vaccination expired on {fecha}. If your pet has had it again, update it.",
      "salud.guardarFecha": "Save the date",
      "salud.error.rabia": "The date, like this: 14/03/2027. Leave it empty if it isn't on record.",
      "salud.guardada": "Last saved on {fecha}.",
      "salud.declarado":
        "What you write here is marked as “declared by the owner”: it doesn't carry the same weight as a report signed by a clinic.",
      "salud.placaSinActualizar": "The tag hasn't been updated",
      "salud.placaSinActualizarTexto": "The record has been saved. The tag will be updated the next time you save.",
      "salud.noGuardada": "Couldn't save",
      "salud.noGuardadaTexto": "Check your connection and try again.",
    },
    fr: {
      "salud.intro":
        "Ce qu'un vétérinaire qui ne connaît pas votre animal doit savoir avant de lui donner quoi que ce soit. Elle est enregistrée chiffrée avec votre clé : personne ne la voit tant que vous ne la montrez pas.",
      "salud.basico": "L'essentiel",
      "salud.especie": "Espèce",
      "salud.especie.dog": "Chien",
      "salud.especie.cat": "Chat",
      "salud.especie.ferret": "Furet",
      "salud.especie.rabbit": "Lapin",
      "salud.especie.bird": "Oiseau",
      "salud.especie.rodent": "Rongeur",
      "salud.especie.reptile": "Reptile",
      "salud.sexo": "Sexe",
      "salud.sexo.hembra": "Femelle",
      "salud.sexo.macho": "Mâle",
      "salud.si": "Oui",
      "salud.no": "Non",
      "salud.esterilizado": "Stérilisé",
      "salud.esterilizada": "Stérilisée",
      "salud.esterilizacion": "Stérilisation",
      "salud.raza": "Race",
      "salud.razaEjemplo": "Croisé, labrador…",
      "salud.nacimiento": "Date de naissance",
      "salud.nacimientoEdad": "Date de naissance · {edad}",
      "salud.edad.menosMes": "moins d'1 mois",
      "salud.edad.mes.uno": "1 mois",
      "salud.edad.mes.varios": "{n} mois",
      "salud.edad.ano.uno": "1 an",
      "salud.edad.ano.varios": "{n} ans",
      "salud.peso": "Poids, en kilos",
      "salud.pesoEjemplo": "12,4",
      "salud.chip": "Numéro complet de la puce (facultatif, se termine par {pista})",
      "salud.error.sexo":
        "Indiquez s'il s'agit d'une femelle ou d'un mâle : sans cela, la fiche ne peut pas être montrée.",
      "salud.error.nacimiento": "La date de naissance, comme ceci : 14/05/2021.",
      "salud.error.futura": "La date de naissance ne peut pas être dans le futur.",
      "salud.error.peso": "Le poids, en kilos : par exemple 12,4.",
      "salud.error.chip": "Le numéro de puce n'a pas le bon format.",
      "salud.error.chipPista": "Ce numéro ne se termine pas par {pista}, comme la puce de cet animal. Vérifiez-le.",
      "salud.alergias": "Allergies",
      "salud.alergiasDe": "ALLERGIES DE {nombre}",
      "salud.ningunaRegistrada": "Aucune enregistrée.",
      "salud.quitar": "Retirer",
      "salud.alergiaA": "Allergie à (principe actif ou aliment, pas la marque)",
      "salud.alergiaEjemplo": "Amoxicilline, poulet…",
      "salud.reaccion": "Ce qui se passe",
      "salud.reaccionOtra": "Autre chose",
      "salud.reaccionTexto": "Décrivez-la (affiché sans traduction)",
      "salud.gravedad": "Gravité",
      "salud.gravedad.alta": "Grave",
      "salud.gravedad.media": "Modérée",
      "salud.gravedad.baja": "Légère",
      "salud.anadirAlergia": "Ajouter une allergie",
      "salud.error.sustancia": "Indiquez à quoi il est allergique : un médicament ou un aliment.",
      "salud.error.reaccion": "Décrivez la réaction en quelques mots.",
      "salud.error.muchasAlergias": "Trop d'allergies sont enregistrées. Retirez-en une.",
      "salud.medicacion": "Traitement habituel",
      "salud.sinMedicacion": "Ne prend rien de façon régulière.",
      "salud.principio": "Ce qu'il prend (le principe actif, pas la marque)",
      "salud.principioEjemplo": "Oméprazole",
      "salud.dosis": "Dose",
      "salud.cada": "À quelle fréquence",
      "salud.cada.8": "Toutes les 8 h",
      "salud.cada.12": "Toutes les 12 h",
      "salud.cada.24": "Une fois par jour",
      "salud.cada.48": "Tous les 2 jours",
      "salud.cada.168": "Une fois par semaine",
      "salud.cada.720": "Une fois par mois",
      "salud.cada.horas": "toutes les {n} heures",
      "salud.anadirMedicamento": "Ajouter un médicament",
      "salud.error.principio": "Indiquez ce qu'il prend.",
      "salud.error.muchosMedicamentos": "Trop de médicaments sont enregistrés. Retirez-en un.",
      "salud.cronicas": "Maladies chroniques",
      "salud.cronicaOtra": "Autre",
      "salud.cronicaAnadir": "En ajouter une (seulement celles diagnostiquées par un vétérinaire)",
      "salud.cronicaTexto": "Laquelle (affiché sans traduction)",
      "salud.anadirEnfermedad": "Ajouter la maladie",
      "salud.error.elegir": "Choisissez-en une dans la liste.",
      "salud.error.cual": "Indiquez laquelle.",
      "salud.error.muchasCronicas": "Trop de maladies sont enregistrées. Retirez-en une.",
      "salud.rabia": "Vaccin antirabique",
      "salud.rabiaHasta": "Valable jusqu'au (la date de son carnet de santé)",
      "salud.rabiaCaducada":
        "D'après cette date, le vaccin a expiré le {fecha}. S'il a déjà été refait, mettez la date à jour.",
      "salud.guardarFecha": "Enregistrer la date",
      "salud.error.rabia": "La date, comme ceci : 14/03/2027. Laissez vide si elle n'est pas connue.",
      "salud.guardada": "Dernier enregistrement le {fecha}.",
      "salud.declarado":
        "Ce que vous écrivez ici est indiqué comme « déclaré par le propriétaire » : cela n'a pas le même poids qu'un compte rendu signé par une clinique.",
      "salud.placaSinActualizar": "La médaille n'a pas été mise à jour",
      "salud.placaSinActualizarTexto":
        "La fiche a été enregistrée. La médaille sera mise à jour la prochaine fois que vous enregistrerez.",
      "salud.noGuardada": "Impossible d'enregistrer",
      "salud.noGuardadaTexto": "Vérifiez votre connexion et réessayez.",
    },
  },
);
